package online.shixun.demo.eshop.eshopserviceproduct.dto;

import java.io.Serializable;
import java.util.Date;

public class EshopBrand implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_brand.id
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_brand.is_del
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_brand.update_time
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_brand.create_time
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_brand.brand_name
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_brand.brand_description
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    private String brandDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_brand.brand_logo
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    private String brandLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_brand.id
     *
     * @return the value of eshop_brand.id
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_brand.id
     *
     * @param id the value for eshop_brand.id
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_brand.is_del
     *
     * @return the value of eshop_brand.is_del
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_brand.is_del
     *
     * @param isDel the value for eshop_brand.is_del
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_brand.update_time
     *
     * @return the value of eshop_brand.update_time
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_brand.update_time
     *
     * @param updateTime the value for eshop_brand.update_time
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_brand.create_time
     *
     * @return the value of eshop_brand.create_time
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_brand.create_time
     *
     * @param createTime the value for eshop_brand.create_time
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_brand.brand_name
     *
     * @return the value of eshop_brand.brand_name
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_brand.brand_name
     *
     * @param brandName the value for eshop_brand.brand_name
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_brand.brand_description
     *
     * @return the value of eshop_brand.brand_description
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public String getBrandDescription() {
        return brandDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_brand.brand_description
     *
     * @param brandDescription the value for eshop_brand.brand_description
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public void setBrandDescription(String brandDescription) {
        this.brandDescription = brandDescription == null ? null : brandDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_brand.brand_logo
     *
     * @return the value of eshop_brand.brand_logo
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public String getBrandLogo() {
        return brandLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_brand.brand_logo
     *
     * @param brandLogo the value for eshop_brand.brand_logo
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    public void setBrandLogo(String brandLogo) {
        this.brandLogo = brandLogo == null ? null : brandLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_brand
     *
     * @mbg.generated Fri May 11 10:31:39 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDel=").append(isDel);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", brandName=").append(brandName);
        sb.append(", brandDescription=").append(brandDescription);
        sb.append(", brandLogo=").append(brandLogo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}