package online.shixun.demo.eshop.eshopserviceproduct.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EshopSkuCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public EshopSkuCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Integer value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Integer value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Integer value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Integer value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Integer value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Integer> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Integer> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Integer value1, Integer value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Integer value1, Integer value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterionForJDBCDate("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andColorIdIsNull() {
            addCriterion("color_id is null");
            return (Criteria) this;
        }

        public Criteria andColorIdIsNotNull() {
            addCriterion("color_id is not null");
            return (Criteria) this;
        }

        public Criteria andColorIdEqualTo(String value) {
            addCriterion("color_id =", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdNotEqualTo(String value) {
            addCriterion("color_id <>", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdGreaterThan(String value) {
            addCriterion("color_id >", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdGreaterThanOrEqualTo(String value) {
            addCriterion("color_id >=", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdLessThan(String value) {
            addCriterion("color_id <", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdLessThanOrEqualTo(String value) {
            addCriterion("color_id <=", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdLike(String value) {
            addCriterion("color_id like", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdNotLike(String value) {
            addCriterion("color_id not like", value, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdIn(List<String> values) {
            addCriterion("color_id in", values, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdNotIn(List<String> values) {
            addCriterion("color_id not in", values, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdBetween(String value1, String value2) {
            addCriterion("color_id between", value1, value2, "colorId");
            return (Criteria) this;
        }

        public Criteria andColorIdNotBetween(String value1, String value2) {
            addCriterion("color_id not between", value1, value2, "colorId");
            return (Criteria) this;
        }

        public Criteria andSizeIdIsNull() {
            addCriterion("size_id is null");
            return (Criteria) this;
        }

        public Criteria andSizeIdIsNotNull() {
            addCriterion("size_id is not null");
            return (Criteria) this;
        }

        public Criteria andSizeIdEqualTo(String value) {
            addCriterion("size_id =", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdNotEqualTo(String value) {
            addCriterion("size_id <>", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdGreaterThan(String value) {
            addCriterion("size_id >", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdGreaterThanOrEqualTo(String value) {
            addCriterion("size_id >=", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdLessThan(String value) {
            addCriterion("size_id <", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdLessThanOrEqualTo(String value) {
            addCriterion("size_id <=", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdLike(String value) {
            addCriterion("size_id like", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdNotLike(String value) {
            addCriterion("size_id not like", value, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdIn(List<String> values) {
            addCriterion("size_id in", values, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdNotIn(List<String> values) {
            addCriterion("size_id not in", values, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdBetween(String value1, String value2) {
            addCriterion("size_id between", value1, value2, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSizeIdNotBetween(String value1, String value2) {
            addCriterion("size_id not between", value1, value2, "sizeId");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeIsNull() {
            addCriterion("sku_delive_fee is null");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeIsNotNull() {
            addCriterion("sku_delive_fee is not null");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeEqualTo(Float value) {
            addCriterion("sku_delive_fee =", value, "skuDeliveFee");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeNotEqualTo(Float value) {
            addCriterion("sku_delive_fee <>", value, "skuDeliveFee");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeGreaterThan(Float value) {
            addCriterion("sku_delive_fee >", value, "skuDeliveFee");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeGreaterThanOrEqualTo(Float value) {
            addCriterion("sku_delive_fee >=", value, "skuDeliveFee");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeLessThan(Float value) {
            addCriterion("sku_delive_fee <", value, "skuDeliveFee");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeLessThanOrEqualTo(Float value) {
            addCriterion("sku_delive_fee <=", value, "skuDeliveFee");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeIn(List<Float> values) {
            addCriterion("sku_delive_fee in", values, "skuDeliveFee");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeNotIn(List<Float> values) {
            addCriterion("sku_delive_fee not in", values, "skuDeliveFee");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeBetween(Float value1, Float value2) {
            addCriterion("sku_delive_fee between", value1, value2, "skuDeliveFee");
            return (Criteria) this;
        }

        public Criteria andSkuDeliveFeeNotBetween(Float value1, Float value2) {
            addCriterion("sku_delive_fee not between", value1, value2, "skuDeliveFee");
            return (Criteria) this;
        }

        public Criteria andSkuPriceIsNull() {
            addCriterion("sku_price is null");
            return (Criteria) this;
        }

        public Criteria andSkuPriceIsNotNull() {
            addCriterion("sku_price is not null");
            return (Criteria) this;
        }

        public Criteria andSkuPriceEqualTo(Float value) {
            addCriterion("sku_price =", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceNotEqualTo(Float value) {
            addCriterion("sku_price <>", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceGreaterThan(Float value) {
            addCriterion("sku_price >", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("sku_price >=", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceLessThan(Float value) {
            addCriterion("sku_price <", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceLessThanOrEqualTo(Float value) {
            addCriterion("sku_price <=", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceIn(List<Float> values) {
            addCriterion("sku_price in", values, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceNotIn(List<Float> values) {
            addCriterion("sku_price not in", values, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceBetween(Float value1, Float value2) {
            addCriterion("sku_price between", value1, value2, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceNotBetween(Float value1, Float value2) {
            addCriterion("sku_price not between", value1, value2, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuStockIsNull() {
            addCriterion("sku_stock is null");
            return (Criteria) this;
        }

        public Criteria andSkuStockIsNotNull() {
            addCriterion("sku_stock is not null");
            return (Criteria) this;
        }

        public Criteria andSkuStockEqualTo(Integer value) {
            addCriterion("sku_stock =", value, "skuStock");
            return (Criteria) this;
        }

        public Criteria andSkuStockNotEqualTo(Integer value) {
            addCriterion("sku_stock <>", value, "skuStock");
            return (Criteria) this;
        }

        public Criteria andSkuStockGreaterThan(Integer value) {
            addCriterion("sku_stock >", value, "skuStock");
            return (Criteria) this;
        }

        public Criteria andSkuStockGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_stock >=", value, "skuStock");
            return (Criteria) this;
        }

        public Criteria andSkuStockLessThan(Integer value) {
            addCriterion("sku_stock <", value, "skuStock");
            return (Criteria) this;
        }

        public Criteria andSkuStockLessThanOrEqualTo(Integer value) {
            addCriterion("sku_stock <=", value, "skuStock");
            return (Criteria) this;
        }

        public Criteria andSkuStockIn(List<Integer> values) {
            addCriterion("sku_stock in", values, "skuStock");
            return (Criteria) this;
        }

        public Criteria andSkuStockNotIn(List<Integer> values) {
            addCriterion("sku_stock not in", values, "skuStock");
            return (Criteria) this;
        }

        public Criteria andSkuStockBetween(Integer value1, Integer value2) {
            addCriterion("sku_stock between", value1, value2, "skuStock");
            return (Criteria) this;
        }

        public Criteria andSkuStockNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_stock not between", value1, value2, "skuStock");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceIsNull() {
            addCriterion("sku_market_price is null");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceIsNotNull() {
            addCriterion("sku_market_price is not null");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceEqualTo(Float value) {
            addCriterion("sku_market_price =", value, "skuMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceNotEqualTo(Float value) {
            addCriterion("sku_market_price <>", value, "skuMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceGreaterThan(Float value) {
            addCriterion("sku_market_price >", value, "skuMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("sku_market_price >=", value, "skuMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceLessThan(Float value) {
            addCriterion("sku_market_price <", value, "skuMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceLessThanOrEqualTo(Float value) {
            addCriterion("sku_market_price <=", value, "skuMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceIn(List<Float> values) {
            addCriterion("sku_market_price in", values, "skuMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceNotIn(List<Float> values) {
            addCriterion("sku_market_price not in", values, "skuMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceBetween(Float value1, Float value2) {
            addCriterion("sku_market_price between", value1, value2, "skuMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuMarketPriceNotBetween(Float value1, Float value2) {
            addCriterion("sku_market_price not between", value1, value2, "skuMarketPrice");
            return (Criteria) this;
        }

        public Criteria andSkuSalesIsNull() {
            addCriterion("sku_sales is null");
            return (Criteria) this;
        }

        public Criteria andSkuSalesIsNotNull() {
            addCriterion("sku_sales is not null");
            return (Criteria) this;
        }

        public Criteria andSkuSalesEqualTo(Integer value) {
            addCriterion("sku_sales =", value, "skuSales");
            return (Criteria) this;
        }

        public Criteria andSkuSalesNotEqualTo(Integer value) {
            addCriterion("sku_sales <>", value, "skuSales");
            return (Criteria) this;
        }

        public Criteria andSkuSalesGreaterThan(Integer value) {
            addCriterion("sku_sales >", value, "skuSales");
            return (Criteria) this;
        }

        public Criteria andSkuSalesGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_sales >=", value, "skuSales");
            return (Criteria) this;
        }

        public Criteria andSkuSalesLessThan(Integer value) {
            addCriterion("sku_sales <", value, "skuSales");
            return (Criteria) this;
        }

        public Criteria andSkuSalesLessThanOrEqualTo(Integer value) {
            addCriterion("sku_sales <=", value, "skuSales");
            return (Criteria) this;
        }

        public Criteria andSkuSalesIn(List<Integer> values) {
            addCriterion("sku_sales in", values, "skuSales");
            return (Criteria) this;
        }

        public Criteria andSkuSalesNotIn(List<Integer> values) {
            addCriterion("sku_sales not in", values, "skuSales");
            return (Criteria) this;
        }

        public Criteria andSkuSalesBetween(Integer value1, Integer value2) {
            addCriterion("sku_sales between", value1, value2, "skuSales");
            return (Criteria) this;
        }

        public Criteria andSkuSalesNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_sales not between", value1, value2, "skuSales");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitIsNull() {
            addCriterion("sku_upper_limit is null");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitIsNotNull() {
            addCriterion("sku_upper_limit is not null");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitEqualTo(Integer value) {
            addCriterion("sku_upper_limit =", value, "skuUpperLimit");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitNotEqualTo(Integer value) {
            addCriterion("sku_upper_limit <>", value, "skuUpperLimit");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitGreaterThan(Integer value) {
            addCriterion("sku_upper_limit >", value, "skuUpperLimit");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_upper_limit >=", value, "skuUpperLimit");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitLessThan(Integer value) {
            addCriterion("sku_upper_limit <", value, "skuUpperLimit");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitLessThanOrEqualTo(Integer value) {
            addCriterion("sku_upper_limit <=", value, "skuUpperLimit");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitIn(List<Integer> values) {
            addCriterion("sku_upper_limit in", values, "skuUpperLimit");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitNotIn(List<Integer> values) {
            addCriterion("sku_upper_limit not in", values, "skuUpperLimit");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitBetween(Integer value1, Integer value2) {
            addCriterion("sku_upper_limit between", value1, value2, "skuUpperLimit");
            return (Criteria) this;
        }

        public Criteria andSkuUpperLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_upper_limit not between", value1, value2, "skuUpperLimit");
            return (Criteria) this;
        }

        public Criteria andSkuLocationIsNull() {
            addCriterion("sku_location is null");
            return (Criteria) this;
        }

        public Criteria andSkuLocationIsNotNull() {
            addCriterion("sku_location is not null");
            return (Criteria) this;
        }

        public Criteria andSkuLocationEqualTo(String value) {
            addCriterion("sku_location =", value, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuLocationNotEqualTo(String value) {
            addCriterion("sku_location <>", value, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuLocationGreaterThan(String value) {
            addCriterion("sku_location >", value, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuLocationGreaterThanOrEqualTo(String value) {
            addCriterion("sku_location >=", value, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuLocationLessThan(String value) {
            addCriterion("sku_location <", value, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuLocationLessThanOrEqualTo(String value) {
            addCriterion("sku_location <=", value, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuLocationLike(String value) {
            addCriterion("sku_location like", value, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuLocationNotLike(String value) {
            addCriterion("sku_location not like", value, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuLocationIn(List<String> values) {
            addCriterion("sku_location in", values, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuLocationNotIn(List<String> values) {
            addCriterion("sku_location not in", values, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuLocationBetween(String value1, String value2) {
            addCriterion("sku_location between", value1, value2, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuLocationNotBetween(String value1, String value2) {
            addCriterion("sku_location not between", value1, value2, "skuLocation");
            return (Criteria) this;
        }

        public Criteria andSkuImgIsNull() {
            addCriterion("sku_img is null");
            return (Criteria) this;
        }

        public Criteria andSkuImgIsNotNull() {
            addCriterion("sku_img is not null");
            return (Criteria) this;
        }

        public Criteria andSkuImgEqualTo(String value) {
            addCriterion("sku_img =", value, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuImgNotEqualTo(String value) {
            addCriterion("sku_img <>", value, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuImgGreaterThan(String value) {
            addCriterion("sku_img >", value, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuImgGreaterThanOrEqualTo(String value) {
            addCriterion("sku_img >=", value, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuImgLessThan(String value) {
            addCriterion("sku_img <", value, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuImgLessThanOrEqualTo(String value) {
            addCriterion("sku_img <=", value, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuImgLike(String value) {
            addCriterion("sku_img like", value, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuImgNotLike(String value) {
            addCriterion("sku_img not like", value, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuImgIn(List<String> values) {
            addCriterion("sku_img in", values, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuImgNotIn(List<String> values) {
            addCriterion("sku_img not in", values, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuImgBetween(String value1, String value2) {
            addCriterion("sku_img between", value1, value2, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuImgNotBetween(String value1, String value2) {
            addCriterion("sku_img not between", value1, value2, "skuImg");
            return (Criteria) this;
        }

        public Criteria andSkuIndexIsNull() {
            addCriterion("sku_index is null");
            return (Criteria) this;
        }

        public Criteria andSkuIndexIsNotNull() {
            addCriterion("sku_index is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIndexEqualTo(Integer value) {
            addCriterion("sku_index =", value, "skuIndex");
            return (Criteria) this;
        }

        public Criteria andSkuIndexNotEqualTo(Integer value) {
            addCriterion("sku_index <>", value, "skuIndex");
            return (Criteria) this;
        }

        public Criteria andSkuIndexGreaterThan(Integer value) {
            addCriterion("sku_index >", value, "skuIndex");
            return (Criteria) this;
        }

        public Criteria andSkuIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_index >=", value, "skuIndex");
            return (Criteria) this;
        }

        public Criteria andSkuIndexLessThan(Integer value) {
            addCriterion("sku_index <", value, "skuIndex");
            return (Criteria) this;
        }

        public Criteria andSkuIndexLessThanOrEqualTo(Integer value) {
            addCriterion("sku_index <=", value, "skuIndex");
            return (Criteria) this;
        }

        public Criteria andSkuIndexIn(List<Integer> values) {
            addCriterion("sku_index in", values, "skuIndex");
            return (Criteria) this;
        }

        public Criteria andSkuIndexNotIn(List<Integer> values) {
            addCriterion("sku_index not in", values, "skuIndex");
            return (Criteria) this;
        }

        public Criteria andSkuIndexBetween(Integer value1, Integer value2) {
            addCriterion("sku_index between", value1, value2, "skuIndex");
            return (Criteria) this;
        }

        public Criteria andSkuIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_index not between", value1, value2, "skuIndex");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNull() {
            addCriterion("sku_name is null");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNotNull() {
            addCriterion("sku_name is not null");
            return (Criteria) this;
        }

        public Criteria andSkuNameEqualTo(String value) {
            addCriterion("sku_name =", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotEqualTo(String value) {
            addCriterion("sku_name <>", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThan(String value) {
            addCriterion("sku_name >", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThanOrEqualTo(String value) {
            addCriterion("sku_name >=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThan(String value) {
            addCriterion("sku_name <", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThanOrEqualTo(String value) {
            addCriterion("sku_name <=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLike(String value) {
            addCriterion("sku_name like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotLike(String value) {
            addCriterion("sku_name not like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameIn(List<String> values) {
            addCriterion("sku_name in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotIn(List<String> values) {
            addCriterion("sku_name not in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameBetween(String value1, String value2) {
            addCriterion("sku_name between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotBetween(String value1, String value2) {
            addCriterion("sku_name not between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andSkuStatusIsNull() {
            addCriterion("sku_status is null");
            return (Criteria) this;
        }

        public Criteria andSkuStatusIsNotNull() {
            addCriterion("sku_status is not null");
            return (Criteria) this;
        }

        public Criteria andSkuStatusEqualTo(Integer value) {
            addCriterion("sku_status =", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusNotEqualTo(Integer value) {
            addCriterion("sku_status <>", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusGreaterThan(Integer value) {
            addCriterion("sku_status >", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_status >=", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusLessThan(Integer value) {
            addCriterion("sku_status <", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sku_status <=", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusIn(List<Integer> values) {
            addCriterion("sku_status in", values, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusNotIn(List<Integer> values) {
            addCriterion("sku_status not in", values, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusBetween(Integer value1, Integer value2) {
            addCriterion("sku_status between", value1, value2, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_status not between", value1, value2, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuTypeIsNull() {
            addCriterion("sku_type is null");
            return (Criteria) this;
        }

        public Criteria andSkuTypeIsNotNull() {
            addCriterion("sku_type is not null");
            return (Criteria) this;
        }

        public Criteria andSkuTypeEqualTo(Integer value) {
            addCriterion("sku_type =", value, "skuType");
            return (Criteria) this;
        }

        public Criteria andSkuTypeNotEqualTo(Integer value) {
            addCriterion("sku_type <>", value, "skuType");
            return (Criteria) this;
        }

        public Criteria andSkuTypeGreaterThan(Integer value) {
            addCriterion("sku_type >", value, "skuType");
            return (Criteria) this;
        }

        public Criteria andSkuTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_type >=", value, "skuType");
            return (Criteria) this;
        }

        public Criteria andSkuTypeLessThan(Integer value) {
            addCriterion("sku_type <", value, "skuType");
            return (Criteria) this;
        }

        public Criteria andSkuTypeLessThanOrEqualTo(Integer value) {
            addCriterion("sku_type <=", value, "skuType");
            return (Criteria) this;
        }

        public Criteria andSkuTypeIn(List<Integer> values) {
            addCriterion("sku_type in", values, "skuType");
            return (Criteria) this;
        }

        public Criteria andSkuTypeNotIn(List<Integer> values) {
            addCriterion("sku_type not in", values, "skuType");
            return (Criteria) this;
        }

        public Criteria andSkuTypeBetween(Integer value1, Integer value2) {
            addCriterion("sku_type between", value1, value2, "skuType");
            return (Criteria) this;
        }

        public Criteria andSkuTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_type not between", value1, value2, "skuType");
            return (Criteria) this;
        }

        public Criteria andSkuRankIsNull() {
            addCriterion("sku_rank is null");
            return (Criteria) this;
        }

        public Criteria andSkuRankIsNotNull() {
            addCriterion("sku_rank is not null");
            return (Criteria) this;
        }

        public Criteria andSkuRankEqualTo(Float value) {
            addCriterion("sku_rank =", value, "skuRank");
            return (Criteria) this;
        }

        public Criteria andSkuRankNotEqualTo(Float value) {
            addCriterion("sku_rank <>", value, "skuRank");
            return (Criteria) this;
        }

        public Criteria andSkuRankGreaterThan(Float value) {
            addCriterion("sku_rank >", value, "skuRank");
            return (Criteria) this;
        }

        public Criteria andSkuRankGreaterThanOrEqualTo(Float value) {
            addCriterion("sku_rank >=", value, "skuRank");
            return (Criteria) this;
        }

        public Criteria andSkuRankLessThan(Float value) {
            addCriterion("sku_rank <", value, "skuRank");
            return (Criteria) this;
        }

        public Criteria andSkuRankLessThanOrEqualTo(Float value) {
            addCriterion("sku_rank <=", value, "skuRank");
            return (Criteria) this;
        }

        public Criteria andSkuRankIn(List<Float> values) {
            addCriterion("sku_rank in", values, "skuRank");
            return (Criteria) this;
        }

        public Criteria andSkuRankNotIn(List<Float> values) {
            addCriterion("sku_rank not in", values, "skuRank");
            return (Criteria) this;
        }

        public Criteria andSkuRankBetween(Float value1, Float value2) {
            addCriterion("sku_rank between", value1, value2, "skuRank");
            return (Criteria) this;
        }

        public Criteria andSkuRankNotBetween(Float value1, Float value2) {
            addCriterion("sku_rank not between", value1, value2, "skuRank");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_sku
     *
     * @mbg.generated do_not_delete_during_merge Fri May 11 10:31:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}