package online.shixun.demo.eshop.eshopserviceproduct.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EshopProduct implements Serializable {

    //特殊属性
    private List<EshopImg> imgs = new ArrayList<>();//图片
    private List<EshopSku> skus = new ArrayList<>();//销售单元
    private  EshopBrand brand;

    public List<EshopImg> getImgs() {
        return imgs;
    }

    public void setImgs(List<EshopImg> imgs) {
        this.imgs = imgs;
    }

    public List<EshopSku> getSkus() {
        return skus;
    }

    public void setSkus(List<EshopSku> skus) {
        this.skus = skus;
    }

    public EshopBrand getBrand() {
        return brand;
    }

    public void setBrand(EshopBrand brand) {
        this.brand = brand;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.is_del
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.create_time
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.update_time
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.brand_id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.type_id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.product_name
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.product_weight
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String productWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.product_is_new
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer productIsNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.product_is_hot
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer productIsHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.product_is_commend
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer productIsCommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.product_is_show
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer productIsShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.product_sales
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer productSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.product_colors
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String productColors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.product_sizes
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String productSizes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.product_features
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String productFeatures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.check_user_id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String checkUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_product.product_check_time
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Date productCheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.id
     *
     * @return the value of eshop_product.id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.id
     *
     * @param id the value for eshop_product.id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.is_del
     *
     * @return the value of eshop_product.is_del
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.is_del
     *
     * @param isDel the value for eshop_product.is_del
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.create_time
     *
     * @return the value of eshop_product.create_time
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.create_time
     *
     * @param createTime the value for eshop_product.create_time
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.update_time
     *
     * @return the value of eshop_product.update_time
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.update_time
     *
     * @param updateTime the value for eshop_product.update_time
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.brand_id
     *
     * @return the value of eshop_product.brand_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.brand_id
     *
     * @param brandId the value for eshop_product.brand_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.type_id
     *
     * @return the value of eshop_product.type_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.type_id
     *
     * @param typeId the value for eshop_product.type_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.product_name
     *
     * @return the value of eshop_product.product_name
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.product_name
     *
     * @param productName the value for eshop_product.product_name
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.product_weight
     *
     * @return the value of eshop_product.product_weight
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getProductWeight() {
        return productWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.product_weight
     *
     * @param productWeight the value for eshop_product.product_weight
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductWeight(String productWeight) {
        this.productWeight = productWeight == null ? null : productWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.product_is_new
     *
     * @return the value of eshop_product.product_is_new
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getProductIsNew() {
        return productIsNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.product_is_new
     *
     * @param productIsNew the value for eshop_product.product_is_new
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductIsNew(Integer productIsNew) {
        this.productIsNew = productIsNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.product_is_hot
     *
     * @return the value of eshop_product.product_is_hot
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getProductIsHot() {
        return productIsHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.product_is_hot
     *
     * @param productIsHot the value for eshop_product.product_is_hot
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductIsHot(Integer productIsHot) {
        this.productIsHot = productIsHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.product_is_commend
     *
     * @return the value of eshop_product.product_is_commend
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getProductIsCommend() {
        return productIsCommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.product_is_commend
     *
     * @param productIsCommend the value for eshop_product.product_is_commend
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductIsCommend(Integer productIsCommend) {
        this.productIsCommend = productIsCommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.product_is_show
     *
     * @return the value of eshop_product.product_is_show
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getProductIsShow() {
        return productIsShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.product_is_show
     *
     * @param productIsShow the value for eshop_product.product_is_show
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductIsShow(Integer productIsShow) {
        this.productIsShow = productIsShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.product_sales
     *
     * @return the value of eshop_product.product_sales
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getProductSales() {
        return productSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.product_sales
     *
     * @param productSales the value for eshop_product.product_sales
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductSales(Integer productSales) {
        this.productSales = productSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.product_colors
     *
     * @return the value of eshop_product.product_colors
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getProductColors() {
        return productColors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.product_colors
     *
     * @param productColors the value for eshop_product.product_colors
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductColors(String productColors) {
        this.productColors = productColors == null ? null : productColors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.product_sizes
     *
     * @return the value of eshop_product.product_sizes
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getProductSizes() {
        return productSizes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.product_sizes
     *
     * @param productSizes the value for eshop_product.product_sizes
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductSizes(String productSizes) {
        this.productSizes = productSizes == null ? null : productSizes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.product_features
     *
     * @return the value of eshop_product.product_features
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getProductFeatures() {
        return productFeatures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.product_features
     *
     * @param productFeatures the value for eshop_product.product_features
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductFeatures(String productFeatures) {
        this.productFeatures = productFeatures == null ? null : productFeatures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.check_user_id
     *
     * @return the value of eshop_product.check_user_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getCheckUserId() {
        return checkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.check_user_id
     *
     * @param checkUserId the value for eshop_product.check_user_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setCheckUserId(String checkUserId) {
        this.checkUserId = checkUserId == null ? null : checkUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_product.product_check_time
     *
     * @return the value of eshop_product.product_check_time
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Date getProductCheckTime() {
        return productCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_product.product_check_time
     *
     * @param productCheckTime the value for eshop_product.product_check_time
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductCheckTime(Date productCheckTime) {
        this.productCheckTime = productCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", brandId=").append(brandId);
        sb.append(", typeId=").append(typeId);
        sb.append(", productName=").append(productName);
        sb.append(", productWeight=").append(productWeight);
        sb.append(", productIsNew=").append(productIsNew);
        sb.append(", productIsHot=").append(productIsHot);
        sb.append(", productIsCommend=").append(productIsCommend);
        sb.append(", productIsShow=").append(productIsShow);
        sb.append(", productSales=").append(productSales);
        sb.append(", productColors=").append(productColors);
        sb.append(", productSizes=").append(productSizes);
        sb.append(", productFeatures=").append(productFeatures);
        sb.append(", checkUserId=").append(checkUserId);
        sb.append(", productCheckTime=").append(productCheckTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}