package online.shixun.demo.eshop.eshopserviceproduct.dto;

import java.io.Serializable;
import java.util.Date;

public class EshopSku implements Serializable {

    //特殊属性
    private EshopProduct product;
    private EshopColor color;
    private EshopSize size;

    public EshopProduct getProduct() {
        return product;
    }

    public void setProduct(EshopProduct product) {
        this.product = product;
    }

    public EshopColor getColor() {
        return color;
    }

    public void setColor(EshopColor color) {
        this.color = color;
    }


    public EshopSize getSize() {
        return size;
    }

    public void setSize(EshopSize size) {
        this.size = size;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.is_del
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.create_time
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.update_time
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.product_id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.color_id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String colorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.size_id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String sizeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_delive_fee
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Float skuDeliveFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_price
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Float skuPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_stock
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer skuStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_market_price
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Float skuMarketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_sales
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer skuSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_upper_limit
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer skuUpperLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_location
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String skuLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_img
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String skuImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_index
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer skuIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_name
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.create_user_id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.update_user_id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_status
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer skuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_type
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer skuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_sku.sku_rank
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Float skuRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.id
     *
     * @return the value of eshop_sku.id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.id
     *
     * @param id the value for eshop_sku.id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.is_del
     *
     * @return the value of eshop_sku.is_del
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.is_del
     *
     * @param isDel the value for eshop_sku.is_del
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.create_time
     *
     * @return the value of eshop_sku.create_time
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.create_time
     *
     * @param createTime the value for eshop_sku.create_time
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.update_time
     *
     * @return the value of eshop_sku.update_time
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.update_time
     *
     * @param updateTime the value for eshop_sku.update_time
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.product_id
     *
     * @return the value of eshop_sku.product_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.product_id
     *
     * @param productId the value for eshop_sku.product_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.color_id
     *
     * @return the value of eshop_sku.color_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getColorId() {
        return colorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.color_id
     *
     * @param colorId the value for eshop_sku.color_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setColorId(String colorId) {
        this.colorId = colorId == null ? null : colorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.size_id
     *
     * @return the value of eshop_sku.size_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getSizeId() {
        return sizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.size_id
     *
     * @param sizeId the value for eshop_sku.size_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSizeId(String sizeId) {
        this.sizeId = sizeId == null ? null : sizeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_delive_fee
     *
     * @return the value of eshop_sku.sku_delive_fee
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Float getSkuDeliveFee() {
        return skuDeliveFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_delive_fee
     *
     * @param skuDeliveFee the value for eshop_sku.sku_delive_fee
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuDeliveFee(Float skuDeliveFee) {
        this.skuDeliveFee = skuDeliveFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_price
     *
     * @return the value of eshop_sku.sku_price
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Float getSkuPrice() {
        return skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_price
     *
     * @param skuPrice the value for eshop_sku.sku_price
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuPrice(Float skuPrice) {
        this.skuPrice = skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_stock
     *
     * @return the value of eshop_sku.sku_stock
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getSkuStock() {
        return skuStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_stock
     *
     * @param skuStock the value for eshop_sku.sku_stock
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuStock(Integer skuStock) {
        this.skuStock = skuStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_market_price
     *
     * @return the value of eshop_sku.sku_market_price
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Float getSkuMarketPrice() {
        return skuMarketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_market_price
     *
     * @param skuMarketPrice the value for eshop_sku.sku_market_price
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuMarketPrice(Float skuMarketPrice) {
        this.skuMarketPrice = skuMarketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_sales
     *
     * @return the value of eshop_sku.sku_sales
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getSkuSales() {
        return skuSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_sales
     *
     * @param skuSales the value for eshop_sku.sku_sales
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuSales(Integer skuSales) {
        this.skuSales = skuSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_upper_limit
     *
     * @return the value of eshop_sku.sku_upper_limit
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getSkuUpperLimit() {
        return skuUpperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_upper_limit
     *
     * @param skuUpperLimit the value for eshop_sku.sku_upper_limit
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuUpperLimit(Integer skuUpperLimit) {
        this.skuUpperLimit = skuUpperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_location
     *
     * @return the value of eshop_sku.sku_location
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getSkuLocation() {
        return skuLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_location
     *
     * @param skuLocation the value for eshop_sku.sku_location
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuLocation(String skuLocation) {
        this.skuLocation = skuLocation == null ? null : skuLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_img
     *
     * @return the value of eshop_sku.sku_img
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getSkuImg() {
        return skuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_img
     *
     * @param skuImg the value for eshop_sku.sku_img
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuImg(String skuImg) {
        this.skuImg = skuImg == null ? null : skuImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_index
     *
     * @return the value of eshop_sku.sku_index
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getSkuIndex() {
        return skuIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_index
     *
     * @param skuIndex the value for eshop_sku.sku_index
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuIndex(Integer skuIndex) {
        this.skuIndex = skuIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_name
     *
     * @return the value of eshop_sku.sku_name
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_name
     *
     * @param skuName the value for eshop_sku.sku_name
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.create_user_id
     *
     * @return the value of eshop_sku.create_user_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.create_user_id
     *
     * @param createUserId the value for eshop_sku.create_user_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.update_user_id
     *
     * @return the value of eshop_sku.update_user_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.update_user_id
     *
     * @param updateUserId the value for eshop_sku.update_user_id
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_status
     *
     * @return the value of eshop_sku.sku_status
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getSkuStatus() {
        return skuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_status
     *
     * @param skuStatus the value for eshop_sku.sku_status
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuStatus(Integer skuStatus) {
        this.skuStatus = skuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_type
     *
     * @return the value of eshop_sku.sku_type
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getSkuType() {
        return skuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_type
     *
     * @param skuType the value for eshop_sku.sku_type
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuType(Integer skuType) {
        this.skuType = skuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_sku.sku_rank
     *
     * @return the value of eshop_sku.sku_rank
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Float getSkuRank() {
        return skuRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_sku.sku_rank
     *
     * @param skuRank the value for eshop_sku.sku_rank
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setSkuRank(Float skuRank) {
        this.skuRank = skuRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_sku
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", productId=").append(productId);
        sb.append(", colorId=").append(colorId);
        sb.append(", sizeId=").append(sizeId);
        sb.append(", skuDeliveFee=").append(skuDeliveFee);
        sb.append(", skuPrice=").append(skuPrice);
        sb.append(", skuStock=").append(skuStock);
        sb.append(", skuMarketPrice=").append(skuMarketPrice);
        sb.append(", skuSales=").append(skuSales);
        sb.append(", skuUpperLimit=").append(skuUpperLimit);
        sb.append(", skuLocation=").append(skuLocation);
        sb.append(", skuImg=").append(skuImg);
        sb.append(", skuIndex=").append(skuIndex);
        sb.append(", skuName=").append(skuName);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", updateUserId=").append(updateUserId);
        sb.append(", skuStatus=").append(skuStatus);
        sb.append(", skuType=").append(skuType);
        sb.append(", skuRank=").append(skuRank);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}