package online.shixun.demo.eshop.eshopserviceproduct.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EshopProductCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public EshopProductCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Integer value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Integer value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Integer value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Integer value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Integer value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Integer> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Integer> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Integer value1, Integer value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Integer value1, Integer value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterionForJDBCDate("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("brand_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("brand_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(String value) {
            addCriterion("brand_id =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(String value) {
            addCriterion("brand_id <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(String value) {
            addCriterion("brand_id >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(String value) {
            addCriterion("brand_id >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(String value) {
            addCriterion("brand_id <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(String value) {
            addCriterion("brand_id <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLike(String value) {
            addCriterion("brand_id like", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotLike(String value) {
            addCriterion("brand_id not like", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<String> values) {
            addCriterion("brand_id in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<String> values) {
            addCriterion("brand_id not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(String value1, String value2) {
            addCriterion("brand_id between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(String value1, String value2) {
            addCriterion("brand_id not between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNull() {
            addCriterion("type_id is null");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNotNull() {
            addCriterion("type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTypeIdEqualTo(String value) {
            addCriterion("type_id =", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotEqualTo(String value) {
            addCriterion("type_id <>", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThan(String value) {
            addCriterion("type_id >", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("type_id >=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThan(String value) {
            addCriterion("type_id <", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThanOrEqualTo(String value) {
            addCriterion("type_id <=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLike(String value) {
            addCriterion("type_id like", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotLike(String value) {
            addCriterion("type_id not like", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIn(List<String> values) {
            addCriterion("type_id in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotIn(List<String> values) {
            addCriterion("type_id not in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdBetween(String value1, String value2) {
            addCriterion("type_id between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotBetween(String value1, String value2) {
            addCriterion("type_id not between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductWeightIsNull() {
            addCriterion("product_weight is null");
            return (Criteria) this;
        }

        public Criteria andProductWeightIsNotNull() {
            addCriterion("product_weight is not null");
            return (Criteria) this;
        }

        public Criteria andProductWeightEqualTo(String value) {
            addCriterion("product_weight =", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightNotEqualTo(String value) {
            addCriterion("product_weight <>", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightGreaterThan(String value) {
            addCriterion("product_weight >", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightGreaterThanOrEqualTo(String value) {
            addCriterion("product_weight >=", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightLessThan(String value) {
            addCriterion("product_weight <", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightLessThanOrEqualTo(String value) {
            addCriterion("product_weight <=", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightLike(String value) {
            addCriterion("product_weight like", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightNotLike(String value) {
            addCriterion("product_weight not like", value, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightIn(List<String> values) {
            addCriterion("product_weight in", values, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightNotIn(List<String> values) {
            addCriterion("product_weight not in", values, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightBetween(String value1, String value2) {
            addCriterion("product_weight between", value1, value2, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductWeightNotBetween(String value1, String value2) {
            addCriterion("product_weight not between", value1, value2, "productWeight");
            return (Criteria) this;
        }

        public Criteria andProductIsNewIsNull() {
            addCriterion("product_is_new is null");
            return (Criteria) this;
        }

        public Criteria andProductIsNewIsNotNull() {
            addCriterion("product_is_new is not null");
            return (Criteria) this;
        }

        public Criteria andProductIsNewEqualTo(Integer value) {
            addCriterion("product_is_new =", value, "productIsNew");
            return (Criteria) this;
        }

        public Criteria andProductIsNewNotEqualTo(Integer value) {
            addCriterion("product_is_new <>", value, "productIsNew");
            return (Criteria) this;
        }

        public Criteria andProductIsNewGreaterThan(Integer value) {
            addCriterion("product_is_new >", value, "productIsNew");
            return (Criteria) this;
        }

        public Criteria andProductIsNewGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_is_new >=", value, "productIsNew");
            return (Criteria) this;
        }

        public Criteria andProductIsNewLessThan(Integer value) {
            addCriterion("product_is_new <", value, "productIsNew");
            return (Criteria) this;
        }

        public Criteria andProductIsNewLessThanOrEqualTo(Integer value) {
            addCriterion("product_is_new <=", value, "productIsNew");
            return (Criteria) this;
        }

        public Criteria andProductIsNewIn(List<Integer> values) {
            addCriterion("product_is_new in", values, "productIsNew");
            return (Criteria) this;
        }

        public Criteria andProductIsNewNotIn(List<Integer> values) {
            addCriterion("product_is_new not in", values, "productIsNew");
            return (Criteria) this;
        }

        public Criteria andProductIsNewBetween(Integer value1, Integer value2) {
            addCriterion("product_is_new between", value1, value2, "productIsNew");
            return (Criteria) this;
        }

        public Criteria andProductIsNewNotBetween(Integer value1, Integer value2) {
            addCriterion("product_is_new not between", value1, value2, "productIsNew");
            return (Criteria) this;
        }

        public Criteria andProductIsHotIsNull() {
            addCriterion("product_is_hot is null");
            return (Criteria) this;
        }

        public Criteria andProductIsHotIsNotNull() {
            addCriterion("product_is_hot is not null");
            return (Criteria) this;
        }

        public Criteria andProductIsHotEqualTo(Integer value) {
            addCriterion("product_is_hot =", value, "productIsHot");
            return (Criteria) this;
        }

        public Criteria andProductIsHotNotEqualTo(Integer value) {
            addCriterion("product_is_hot <>", value, "productIsHot");
            return (Criteria) this;
        }

        public Criteria andProductIsHotGreaterThan(Integer value) {
            addCriterion("product_is_hot >", value, "productIsHot");
            return (Criteria) this;
        }

        public Criteria andProductIsHotGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_is_hot >=", value, "productIsHot");
            return (Criteria) this;
        }

        public Criteria andProductIsHotLessThan(Integer value) {
            addCriterion("product_is_hot <", value, "productIsHot");
            return (Criteria) this;
        }

        public Criteria andProductIsHotLessThanOrEqualTo(Integer value) {
            addCriterion("product_is_hot <=", value, "productIsHot");
            return (Criteria) this;
        }

        public Criteria andProductIsHotIn(List<Integer> values) {
            addCriterion("product_is_hot in", values, "productIsHot");
            return (Criteria) this;
        }

        public Criteria andProductIsHotNotIn(List<Integer> values) {
            addCriterion("product_is_hot not in", values, "productIsHot");
            return (Criteria) this;
        }

        public Criteria andProductIsHotBetween(Integer value1, Integer value2) {
            addCriterion("product_is_hot between", value1, value2, "productIsHot");
            return (Criteria) this;
        }

        public Criteria andProductIsHotNotBetween(Integer value1, Integer value2) {
            addCriterion("product_is_hot not between", value1, value2, "productIsHot");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendIsNull() {
            addCriterion("product_is_commend is null");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendIsNotNull() {
            addCriterion("product_is_commend is not null");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendEqualTo(Integer value) {
            addCriterion("product_is_commend =", value, "productIsCommend");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendNotEqualTo(Integer value) {
            addCriterion("product_is_commend <>", value, "productIsCommend");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendGreaterThan(Integer value) {
            addCriterion("product_is_commend >", value, "productIsCommend");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_is_commend >=", value, "productIsCommend");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendLessThan(Integer value) {
            addCriterion("product_is_commend <", value, "productIsCommend");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendLessThanOrEqualTo(Integer value) {
            addCriterion("product_is_commend <=", value, "productIsCommend");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendIn(List<Integer> values) {
            addCriterion("product_is_commend in", values, "productIsCommend");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendNotIn(List<Integer> values) {
            addCriterion("product_is_commend not in", values, "productIsCommend");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendBetween(Integer value1, Integer value2) {
            addCriterion("product_is_commend between", value1, value2, "productIsCommend");
            return (Criteria) this;
        }

        public Criteria andProductIsCommendNotBetween(Integer value1, Integer value2) {
            addCriterion("product_is_commend not between", value1, value2, "productIsCommend");
            return (Criteria) this;
        }

        public Criteria andProductIsShowIsNull() {
            addCriterion("product_is_show is null");
            return (Criteria) this;
        }

        public Criteria andProductIsShowIsNotNull() {
            addCriterion("product_is_show is not null");
            return (Criteria) this;
        }

        public Criteria andProductIsShowEqualTo(Integer value) {
            addCriterion("product_is_show =", value, "productIsShow");
            return (Criteria) this;
        }

        public Criteria andProductIsShowNotEqualTo(Integer value) {
            addCriterion("product_is_show <>", value, "productIsShow");
            return (Criteria) this;
        }

        public Criteria andProductIsShowGreaterThan(Integer value) {
            addCriterion("product_is_show >", value, "productIsShow");
            return (Criteria) this;
        }

        public Criteria andProductIsShowGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_is_show >=", value, "productIsShow");
            return (Criteria) this;
        }

        public Criteria andProductIsShowLessThan(Integer value) {
            addCriterion("product_is_show <", value, "productIsShow");
            return (Criteria) this;
        }

        public Criteria andProductIsShowLessThanOrEqualTo(Integer value) {
            addCriterion("product_is_show <=", value, "productIsShow");
            return (Criteria) this;
        }

        public Criteria andProductIsShowIn(List<Integer> values) {
            addCriterion("product_is_show in", values, "productIsShow");
            return (Criteria) this;
        }

        public Criteria andProductIsShowNotIn(List<Integer> values) {
            addCriterion("product_is_show not in", values, "productIsShow");
            return (Criteria) this;
        }

        public Criteria andProductIsShowBetween(Integer value1, Integer value2) {
            addCriterion("product_is_show between", value1, value2, "productIsShow");
            return (Criteria) this;
        }

        public Criteria andProductIsShowNotBetween(Integer value1, Integer value2) {
            addCriterion("product_is_show not between", value1, value2, "productIsShow");
            return (Criteria) this;
        }

        public Criteria andProductSalesIsNull() {
            addCriterion("product_sales is null");
            return (Criteria) this;
        }

        public Criteria andProductSalesIsNotNull() {
            addCriterion("product_sales is not null");
            return (Criteria) this;
        }

        public Criteria andProductSalesEqualTo(Integer value) {
            addCriterion("product_sales =", value, "productSales");
            return (Criteria) this;
        }

        public Criteria andProductSalesNotEqualTo(Integer value) {
            addCriterion("product_sales <>", value, "productSales");
            return (Criteria) this;
        }

        public Criteria andProductSalesGreaterThan(Integer value) {
            addCriterion("product_sales >", value, "productSales");
            return (Criteria) this;
        }

        public Criteria andProductSalesGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_sales >=", value, "productSales");
            return (Criteria) this;
        }

        public Criteria andProductSalesLessThan(Integer value) {
            addCriterion("product_sales <", value, "productSales");
            return (Criteria) this;
        }

        public Criteria andProductSalesLessThanOrEqualTo(Integer value) {
            addCriterion("product_sales <=", value, "productSales");
            return (Criteria) this;
        }

        public Criteria andProductSalesIn(List<Integer> values) {
            addCriterion("product_sales in", values, "productSales");
            return (Criteria) this;
        }

        public Criteria andProductSalesNotIn(List<Integer> values) {
            addCriterion("product_sales not in", values, "productSales");
            return (Criteria) this;
        }

        public Criteria andProductSalesBetween(Integer value1, Integer value2) {
            addCriterion("product_sales between", value1, value2, "productSales");
            return (Criteria) this;
        }

        public Criteria andProductSalesNotBetween(Integer value1, Integer value2) {
            addCriterion("product_sales not between", value1, value2, "productSales");
            return (Criteria) this;
        }

        public Criteria andProductColorsIsNull() {
            addCriterion("product_colors is null");
            return (Criteria) this;
        }

        public Criteria andProductColorsIsNotNull() {
            addCriterion("product_colors is not null");
            return (Criteria) this;
        }

        public Criteria andProductColorsEqualTo(String value) {
            addCriterion("product_colors =", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsNotEqualTo(String value) {
            addCriterion("product_colors <>", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsGreaterThan(String value) {
            addCriterion("product_colors >", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsGreaterThanOrEqualTo(String value) {
            addCriterion("product_colors >=", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsLessThan(String value) {
            addCriterion("product_colors <", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsLessThanOrEqualTo(String value) {
            addCriterion("product_colors <=", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsLike(String value) {
            addCriterion("product_colors like", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsNotLike(String value) {
            addCriterion("product_colors not like", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsIn(List<String> values) {
            addCriterion("product_colors in", values, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsNotIn(List<String> values) {
            addCriterion("product_colors not in", values, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsBetween(String value1, String value2) {
            addCriterion("product_colors between", value1, value2, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsNotBetween(String value1, String value2) {
            addCriterion("product_colors not between", value1, value2, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductSizesIsNull() {
            addCriterion("product_sizes is null");
            return (Criteria) this;
        }

        public Criteria andProductSizesIsNotNull() {
            addCriterion("product_sizes is not null");
            return (Criteria) this;
        }

        public Criteria andProductSizesEqualTo(String value) {
            addCriterion("product_sizes =", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesNotEqualTo(String value) {
            addCriterion("product_sizes <>", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesGreaterThan(String value) {
            addCriterion("product_sizes >", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesGreaterThanOrEqualTo(String value) {
            addCriterion("product_sizes >=", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesLessThan(String value) {
            addCriterion("product_sizes <", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesLessThanOrEqualTo(String value) {
            addCriterion("product_sizes <=", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesLike(String value) {
            addCriterion("product_sizes like", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesNotLike(String value) {
            addCriterion("product_sizes not like", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesIn(List<String> values) {
            addCriterion("product_sizes in", values, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesNotIn(List<String> values) {
            addCriterion("product_sizes not in", values, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesBetween(String value1, String value2) {
            addCriterion("product_sizes between", value1, value2, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesNotBetween(String value1, String value2) {
            addCriterion("product_sizes not between", value1, value2, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesIsNull() {
            addCriterion("product_features is null");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesIsNotNull() {
            addCriterion("product_features is not null");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesEqualTo(String value) {
            addCriterion("product_features =", value, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesNotEqualTo(String value) {
            addCriterion("product_features <>", value, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesGreaterThan(String value) {
            addCriterion("product_features >", value, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesGreaterThanOrEqualTo(String value) {
            addCriterion("product_features >=", value, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesLessThan(String value) {
            addCriterion("product_features <", value, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesLessThanOrEqualTo(String value) {
            addCriterion("product_features <=", value, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesLike(String value) {
            addCriterion("product_features like", value, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesNotLike(String value) {
            addCriterion("product_features not like", value, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesIn(List<String> values) {
            addCriterion("product_features in", values, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesNotIn(List<String> values) {
            addCriterion("product_features not in", values, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesBetween(String value1, String value2) {
            addCriterion("product_features between", value1, value2, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andProductFeaturesNotBetween(String value1, String value2) {
            addCriterion("product_features not between", value1, value2, "productFeatures");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdIsNull() {
            addCriterion("check_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdIsNotNull() {
            addCriterion("check_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdEqualTo(String value) {
            addCriterion("check_user_id =", value, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdNotEqualTo(String value) {
            addCriterion("check_user_id <>", value, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdGreaterThan(String value) {
            addCriterion("check_user_id >", value, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("check_user_id >=", value, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdLessThan(String value) {
            addCriterion("check_user_id <", value, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdLessThanOrEqualTo(String value) {
            addCriterion("check_user_id <=", value, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdLike(String value) {
            addCriterion("check_user_id like", value, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdNotLike(String value) {
            addCriterion("check_user_id not like", value, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdIn(List<String> values) {
            addCriterion("check_user_id in", values, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdNotIn(List<String> values) {
            addCriterion("check_user_id not in", values, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdBetween(String value1, String value2) {
            addCriterion("check_user_id between", value1, value2, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andCheckUserIdNotBetween(String value1, String value2) {
            addCriterion("check_user_id not between", value1, value2, "checkUserId");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeIsNull() {
            addCriterion("product_check_time is null");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeIsNotNull() {
            addCriterion("product_check_time is not null");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeEqualTo(Date value) {
            addCriterionForJDBCDate("product_check_time =", value, "productCheckTime");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("product_check_time <>", value, "productCheckTime");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("product_check_time >", value, "productCheckTime");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("product_check_time >=", value, "productCheckTime");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeLessThan(Date value) {
            addCriterionForJDBCDate("product_check_time <", value, "productCheckTime");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("product_check_time <=", value, "productCheckTime");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeIn(List<Date> values) {
            addCriterionForJDBCDate("product_check_time in", values, "productCheckTime");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("product_check_time not in", values, "productCheckTime");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("product_check_time between", value1, value2, "productCheckTime");
            return (Criteria) this;
        }

        public Criteria andProductCheckTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("product_check_time not between", value1, value2, "productCheckTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_product
     *
     * @mbg.generated do_not_delete_during_merge Fri May 11 10:31:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}