package online.shixun.demo.eshop.eshopservicetype.dto;

import java.io.Serializable;
import java.util.Date;

public class EshopType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.is_del
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.create_time
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.update_time
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.type_name
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.type_parent_id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String typeParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.type_note
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String typeNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.type_url
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String typeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.type_image
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String typeImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.type_ico
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String typeIco;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.type_index
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private Integer typeIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_type.type_description
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private String typeDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_type
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.id
     *
     * @return the value of eshop_type.id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.id
     *
     * @param id the value for eshop_type.id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.is_del
     *
     * @return the value of eshop_type.is_del
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.is_del
     *
     * @param isDel the value for eshop_type.is_del
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.create_time
     *
     * @return the value of eshop_type.create_time
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.create_time
     *
     * @param createTime the value for eshop_type.create_time
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.update_time
     *
     * @return the value of eshop_type.update_time
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.update_time
     *
     * @param updateTime the value for eshop_type.update_time
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.type_name
     *
     * @return the value of eshop_type.type_name
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.type_name
     *
     * @param typeName the value for eshop_type.type_name
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.type_parent_id
     *
     * @return the value of eshop_type.type_parent_id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getTypeParentId() {
        return typeParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.type_parent_id
     *
     * @param typeParentId the value for eshop_type.type_parent_id
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setTypeParentId(String typeParentId) {
        this.typeParentId = typeParentId == null ? null : typeParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.type_note
     *
     * @return the value of eshop_type.type_note
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getTypeNote() {
        return typeNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.type_note
     *
     * @param typeNote the value for eshop_type.type_note
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setTypeNote(String typeNote) {
        this.typeNote = typeNote == null ? null : typeNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.type_url
     *
     * @return the value of eshop_type.type_url
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getTypeUrl() {
        return typeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.type_url
     *
     * @param typeUrl the value for eshop_type.type_url
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setTypeUrl(String typeUrl) {
        this.typeUrl = typeUrl == null ? null : typeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.type_image
     *
     * @return the value of eshop_type.type_image
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getTypeImage() {
        return typeImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.type_image
     *
     * @param typeImage the value for eshop_type.type_image
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setTypeImage(String typeImage) {
        this.typeImage = typeImage == null ? null : typeImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.type_ico
     *
     * @return the value of eshop_type.type_ico
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getTypeIco() {
        return typeIco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.type_ico
     *
     * @param typeIco the value for eshop_type.type_ico
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setTypeIco(String typeIco) {
        this.typeIco = typeIco == null ? null : typeIco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.type_index
     *
     * @return the value of eshop_type.type_index
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public Integer getTypeIndex() {
        return typeIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.type_index
     *
     * @param typeIndex the value for eshop_type.type_index
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setTypeIndex(Integer typeIndex) {
        this.typeIndex = typeIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_type.type_description
     *
     * @return the value of eshop_type.type_description
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String getTypeDescription() {
        return typeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_type.type_description
     *
     * @param typeDescription the value for eshop_type.type_description
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public void setTypeDescription(String typeDescription) {
        this.typeDescription = typeDescription == null ? null : typeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_type
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", typeName=").append(typeName);
        sb.append(", typeParentId=").append(typeParentId);
        sb.append(", typeNote=").append(typeNote);
        sb.append(", typeUrl=").append(typeUrl);
        sb.append(", typeImage=").append(typeImage);
        sb.append(", typeIco=").append(typeIco);
        sb.append(", typeIndex=").append(typeIndex);
        sb.append(", typeDescription=").append(typeDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}