spring:
  application:
    name: eshop-eureka
server:
  port: 9002
eureka:
  instance:
    hostname: eureka-02
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka,http://192.168.7.11:9001/eureka