spring:
  application:
    name: eshop-eureka
server:
  port: 9000
eureka:
  instance:
    hostname: eureka-00
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka