package online.shixun.demo.eshop.eshopservicetype.module.type.mapper;

import online.shixun.demo.eshop.eshopservicetype.dto.EshopType;
import online.shixun.demo.eshop.eshopservicetype.dto.EshopTypeCriteria;
import online.shixun.demo.eshop.eshopservicetype.dto.EshopTypeCriteria.Criteria;
import online.shixun.demo.eshop.eshopservicetype.dto.EshopTypeCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class EshopTypeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_type
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String countByExample(EshopTypeCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("eshop_type");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_type
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String deleteByExample(EshopTypeCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("eshop_type");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_type
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String insertSelective(EshopType record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("eshop_type");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.VALUES("is_del", "#{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=DATE}");
        }
        
        if (record.getTypeName() != null) {
            sql.VALUES("type_name", "#{typeName,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeParentId() != null) {
            sql.VALUES("type_parent_id", "#{typeParentId,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeNote() != null) {
            sql.VALUES("type_note", "#{typeNote,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeUrl() != null) {
            sql.VALUES("type_url", "#{typeUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeImage() != null) {
            sql.VALUES("type_image", "#{typeImage,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeIco() != null) {
            sql.VALUES("type_ico", "#{typeIco,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeIndex() != null) {
            sql.VALUES("type_index", "#{typeIndex,jdbcType=INTEGER}");
        }
        
        if (record.getTypeDescription() != null) {
            sql.VALUES("type_description", "#{typeDescription,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_type
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String selectByExample(EshopTypeCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("is_del");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.SELECT("type_name");
        sql.SELECT("type_parent_id");
        sql.SELECT("type_note");
        sql.SELECT("type_url");
        sql.SELECT("type_image");
        sql.SELECT("type_ico");
        sql.SELECT("type_index");
        sql.SELECT("type_description");
        sql.FROM("eshop_type");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_type
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        EshopType record = (EshopType) parameter.get("record");
        EshopTypeCriteria example = (EshopTypeCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("eshop_type");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        }
        
        if (record.getTypeName() != null) {
            sql.SET("type_name = #{record.typeName,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeParentId() != null) {
            sql.SET("type_parent_id = #{record.typeParentId,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeNote() != null) {
            sql.SET("type_note = #{record.typeNote,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeUrl() != null) {
            sql.SET("type_url = #{record.typeUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeImage() != null) {
            sql.SET("type_image = #{record.typeImage,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeIco() != null) {
            sql.SET("type_ico = #{record.typeIco,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeIndex() != null) {
            sql.SET("type_index = #{record.typeIndex,jdbcType=INTEGER}");
        }
        
        if (record.getTypeDescription() != null) {
            sql.SET("type_description = #{record.typeDescription,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_type
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_type");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        sql.SET("type_name = #{record.typeName,jdbcType=VARCHAR}");
        sql.SET("type_parent_id = #{record.typeParentId,jdbcType=VARCHAR}");
        sql.SET("type_note = #{record.typeNote,jdbcType=VARCHAR}");
        sql.SET("type_url = #{record.typeUrl,jdbcType=VARCHAR}");
        sql.SET("type_image = #{record.typeImage,jdbcType=VARCHAR}");
        sql.SET("type_ico = #{record.typeIco,jdbcType=VARCHAR}");
        sql.SET("type_index = #{record.typeIndex,jdbcType=INTEGER}");
        sql.SET("type_description = #{record.typeDescription,jdbcType=VARCHAR}");
        
        EshopTypeCriteria example = (EshopTypeCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_type
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String updateByPrimaryKeySelective(EshopType record) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_type");
        
        if (record.getIsDel() != null) {
            sql.SET("is_del = #{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        
        if (record.getTypeName() != null) {
            sql.SET("type_name = #{typeName,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeParentId() != null) {
            sql.SET("type_parent_id = #{typeParentId,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeNote() != null) {
            sql.SET("type_note = #{typeNote,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeUrl() != null) {
            sql.SET("type_url = #{typeUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeImage() != null) {
            sql.SET("type_image = #{typeImage,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeIco() != null) {
            sql.SET("type_ico = #{typeIco,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeIndex() != null) {
            sql.SET("type_index = #{typeIndex,jdbcType=INTEGER}");
        }
        
        if (record.getTypeDescription() != null) {
            sql.SET("type_description = #{typeDescription,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_type
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected void applyWhere(SQL sql, EshopTypeCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}