package online.shixun.demo.eshop.eshopserviceslideshow.module.slideshow.mapper;

import online.shixun.demo.eshop.eshopserviceslideshow.dto.EshopSlideshow;
import online.shixun.demo.eshop.eshopserviceslideshow.dto.EshopSlideshowCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Mapper
public interface EshopSlideshowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @SelectProvider(type=EshopSlideshowSqlProvider.class, method="countByExample")
    long countByExample(EshopSlideshowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @DeleteProvider(type=EshopSlideshowSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopSlideshowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @Delete({
        "delete from eshop_slideshow",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @Insert({
        "insert into eshop_slideshow (id, is_del, ",
        "create_time, update_time, ",
        "slideshow_name, slideshow_url, ",
        "slideshow_index, slideshow_html, ",
        "slideshow_image)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{slideshowName,jdbcType=VARCHAR}, #{slideshowUrl,jdbcType=VARCHAR}, ",
        "#{slideshowIndex,jdbcType=INTEGER}, #{slideshowHtml,jdbcType=VARCHAR}, ",
        "#{slideshowImage,jdbcType=VARCHAR})"
    })
    int insert(EshopSlideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @InsertProvider(type=EshopSlideshowSqlProvider.class, method="insertSelective")
    int insertSelective(EshopSlideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @SelectProvider(type=EshopSlideshowSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="slideshow_name", property="slideshowName", jdbcType=JdbcType.VARCHAR),
        @Result(column="slideshow_url", property="slideshowUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="slideshow_index", property="slideshowIndex", jdbcType=JdbcType.INTEGER),
        @Result(column="slideshow_html", property="slideshowHtml", jdbcType=JdbcType.VARCHAR),
        @Result(column="slideshow_image", property="slideshowImage", jdbcType=JdbcType.VARCHAR)
    })
    List<EshopSlideshow> selectByExample(EshopSlideshowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, slideshow_name, slideshow_url, slideshow_index, ",
        "slideshow_html, slideshow_image",
        "from eshop_slideshow",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="slideshow_name", property="slideshowName", jdbcType=JdbcType.VARCHAR),
        @Result(column="slideshow_url", property="slideshowUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="slideshow_index", property="slideshowIndex", jdbcType=JdbcType.INTEGER),
        @Result(column="slideshow_html", property="slideshowHtml", jdbcType=JdbcType.VARCHAR),
        @Result(column="slideshow_image", property="slideshowImage", jdbcType=JdbcType.VARCHAR)
    })
    EshopSlideshow selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @UpdateProvider(type=EshopSlideshowSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopSlideshow record, @Param("example") EshopSlideshowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @UpdateProvider(type=EshopSlideshowSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopSlideshow record, @Param("example") EshopSlideshowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @UpdateProvider(type=EshopSlideshowSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopSlideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @Update({
        "update eshop_slideshow",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "slideshow_name = #{slideshowName,jdbcType=VARCHAR},",
          "slideshow_url = #{slideshowUrl,jdbcType=VARCHAR},",
          "slideshow_index = #{slideshowIndex,jdbcType=INTEGER},",
          "slideshow_html = #{slideshowHtml,jdbcType=VARCHAR},",
          "slideshow_image = #{slideshowImage,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopSlideshow record);
}