package online.shixun.demo.eshop.eshopserviceslideshow.module.slideshow.mapper;

import java.util.List;
import java.util.Map;

import online.shixun.demo.eshop.eshopserviceslideshow.dto.EshopSlideshow;
import online.shixun.demo.eshop.eshopserviceslideshow.dto.EshopSlideshowCriteria;
import online.shixun.demo.eshop.eshopserviceslideshow.dto.EshopSlideshowCriteria.Criteria;
import online.shixun.demo.eshop.eshopserviceslideshow.dto.EshopSlideshowCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

public class EshopSlideshowSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String countByExample(EshopSlideshowCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("eshop_slideshow");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String deleteByExample(EshopSlideshowCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("eshop_slideshow");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String insertSelective(EshopSlideshow record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("eshop_slideshow");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }

        if (record.getIsDel() != null) {
            sql.VALUES("is_del", "#{isDel,jdbcType=INTEGER}");
        }

        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }

        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=DATE}");
        }

        if (record.getSlideshowName() != null) {
            sql.VALUES("slideshow_name", "#{slideshowName,jdbcType=VARCHAR}");
        }

        if (record.getSlideshowUrl() != null) {
            sql.VALUES("slideshow_url", "#{slideshowUrl,jdbcType=VARCHAR}");
        }

        if (record.getSlideshowIndex() != null) {
            sql.VALUES("slideshow_index", "#{slideshowIndex,jdbcType=INTEGER}");
        }

        if (record.getSlideshowHtml() != null) {
            sql.VALUES("slideshow_html", "#{slideshowHtml,jdbcType=VARCHAR}");
        }

        if (record.getSlideshowImage() != null) {
            sql.VALUES("slideshow_image", "#{slideshowImage,jdbcType=VARCHAR}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String selectByExample(EshopSlideshowCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("is_del");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.SELECT("slideshow_name");
        sql.SELECT("slideshow_url");
        sql.SELECT("slideshow_index");
        sql.SELECT("slideshow_html");
        sql.SELECT("slideshow_image");
        sql.FROM("eshop_slideshow");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        EshopSlideshow record = (EshopSlideshow) parameter.get("record");
        EshopSlideshowCriteria example = (EshopSlideshowCriteria) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("eshop_slideshow");

        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }

        if (record.getIsDel() != null) {
            sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        }

        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        }

        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        }

        if (record.getSlideshowName() != null) {
            sql.SET("slideshow_name = #{record.slideshowName,jdbcType=VARCHAR}");
        }

        if (record.getSlideshowUrl() != null) {
            sql.SET("slideshow_url = #{record.slideshowUrl,jdbcType=VARCHAR}");
        }

        if (record.getSlideshowIndex() != null) {
            sql.SET("slideshow_index = #{record.slideshowIndex,jdbcType=INTEGER}");
        }

        if (record.getSlideshowHtml() != null) {
            sql.SET("slideshow_html = #{record.slideshowHtml,jdbcType=VARCHAR}");
        }

        if (record.getSlideshowImage() != null) {
            sql.SET("slideshow_image = #{record.slideshowImage,jdbcType=VARCHAR}");
        }

        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_slideshow");

        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        sql.SET("slideshow_name = #{record.slideshowName,jdbcType=VARCHAR}");
        sql.SET("slideshow_url = #{record.slideshowUrl,jdbcType=VARCHAR}");
        sql.SET("slideshow_index = #{record.slideshowIndex,jdbcType=INTEGER}");
        sql.SET("slideshow_html = #{record.slideshowHtml,jdbcType=VARCHAR}");
        sql.SET("slideshow_image = #{record.slideshowImage,jdbcType=VARCHAR}");

        EshopSlideshowCriteria example = (EshopSlideshowCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String updateByPrimaryKeySelective(EshopSlideshow record) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_slideshow");

        if (record.getIsDel() != null) {
            sql.SET("is_del = #{isDel,jdbcType=INTEGER}");
        }

        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }

        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }

        if (record.getSlideshowName() != null) {
            sql.SET("slideshow_name = #{slideshowName,jdbcType=VARCHAR}");
        }

        if (record.getSlideshowUrl() != null) {
            sql.SET("slideshow_url = #{slideshowUrl,jdbcType=VARCHAR}");
        }

        if (record.getSlideshowIndex() != null) {
            sql.SET("slideshow_index = #{slideshowIndex,jdbcType=INTEGER}");
        }

        if (record.getSlideshowHtml() != null) {
            sql.SET("slideshow_html = #{slideshowHtml,jdbcType=VARCHAR}");
        }

        if (record.getSlideshowImage() != null) {
            sql.SET("slideshow_image = #{slideshowImage,jdbcType=VARCHAR}");
        }

        sql.WHERE("id = #{id,jdbcType=VARCHAR}");

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    protected void applyWhere(SQL sql, EshopSlideshowCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}