package online.shixun.demo.eshop.eshopserviceproduct.module.product.mapper;

import online.shixun.demo.eshop.eshopserviceproduct.dto.EshopProduct;
import online.shixun.demo.eshop.eshopserviceproduct.dto.EshopProductCriteria;
import online.shixun.demo.eshop.eshopserviceproduct.dto.EshopProductWithBLOBs;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;
import java.util.Set;

@Mapper
public interface EshopProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @SelectProvider(type=EshopProductSqlProvider.class, method="countByExample")
    long countByExample(EshopProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @DeleteProvider(type=EshopProductSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Delete({
        "delete from eshop_product",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Insert({
        "insert into eshop_product (id, is_del, ",
        "create_time, update_time, ",
        "brand_id, type_id, ",
        "product_name, product_weight, ",
        "product_is_new, product_is_hot, ",
        "product_is_commend, product_is_show, ",
        "product_sales, product_colors, ",
        "product_sizes, product_features, ",
        "check_user_id, product_check_time, ",
        "product_description, product_information, ",
        "product_after_sale)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{brandId,jdbcType=VARCHAR}, #{typeId,jdbcType=VARCHAR}, ",
        "#{productName,jdbcType=VARCHAR}, #{productWeight,jdbcType=VARCHAR}, ",
        "#{productIsNew,jdbcType=INTEGER}, #{productIsHot,jdbcType=INTEGER}, ",
        "#{productIsCommend,jdbcType=INTEGER}, #{productIsShow,jdbcType=INTEGER}, ",
        "#{productSales,jdbcType=INTEGER}, #{productColors,jdbcType=VARCHAR}, ",
        "#{productSizes,jdbcType=VARCHAR}, #{productFeatures,jdbcType=VARCHAR}, ",
        "#{checkUserId,jdbcType=VARCHAR}, #{productCheckTime,jdbcType=DATE}, ",
        "#{productDescription,jdbcType=LONGVARCHAR}, #{productInformation,jdbcType=LONGVARCHAR}, ",
        "#{productAfterSale,jdbcType=LONGVARCHAR})"
    })
    int insert(EshopProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @InsertProvider(type=EshopProductSqlProvider.class, method="insertSelective")
    int insertSelective(EshopProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @SelectProvider(type=EshopProductSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="brand_id", property="brandId", jdbcType=JdbcType.VARCHAR),
        @Result(column="type_id", property="typeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_name", property="productName", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_weight", property="productWeight", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_is_new", property="productIsNew", jdbcType=JdbcType.INTEGER),
        @Result(column="product_is_hot", property="productIsHot", jdbcType=JdbcType.INTEGER),
        @Result(column="product_is_commend", property="productIsCommend", jdbcType=JdbcType.INTEGER),
        @Result(column="product_is_show", property="productIsShow", jdbcType=JdbcType.INTEGER),
        @Result(column="product_sales", property="productSales", jdbcType=JdbcType.INTEGER),
        @Result(column="product_colors", property="productColors", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_sizes", property="productSizes", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_features", property="productFeatures", jdbcType=JdbcType.VARCHAR),
        @Result(column="check_user_id", property="checkUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_check_time", property="productCheckTime", jdbcType=JdbcType.DATE),
        @Result(column="product_description", property="productDescription", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="product_information", property="productInformation", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="product_after_sale", property="productAfterSale", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<EshopProductWithBLOBs> selectByExampleWithBLOBs(EshopProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @SelectProvider(type=EshopProductSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="brand_id", property="brandId", jdbcType=JdbcType.VARCHAR),
        @Result(column="type_id", property="typeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_name", property="productName", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_weight", property="productWeight", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_is_new", property="productIsNew", jdbcType=JdbcType.INTEGER),
        @Result(column="product_is_hot", property="productIsHot", jdbcType=JdbcType.INTEGER),
        @Result(column="product_is_commend", property="productIsCommend", jdbcType=JdbcType.INTEGER),
        @Result(column="product_is_show", property="productIsShow", jdbcType=JdbcType.INTEGER),
        @Result(column="product_sales", property="productSales", jdbcType=JdbcType.INTEGER),
        @Result(column="product_colors", property="productColors", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_sizes", property="productSizes", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_features", property="productFeatures", jdbcType=JdbcType.VARCHAR),
        @Result(column="check_user_id", property="checkUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_check_time", property="productCheckTime", jdbcType=JdbcType.DATE)
    })
    List<EshopProduct> selectByExample(EshopProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, brand_id, type_id, product_name, product_weight, ",
        "product_is_new, product_is_hot, product_is_commend, product_is_show, product_sales, ",
        "product_colors, product_sizes, product_features, check_user_id, product_check_time, ",
        "product_description, product_information, product_after_sale",
        "from eshop_product",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="brand_id", property="brandId", jdbcType=JdbcType.VARCHAR),
        @Result(column="type_id", property="typeId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_name", property="productName", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_weight", property="productWeight", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_is_new", property="productIsNew", jdbcType=JdbcType.INTEGER),
        @Result(column="product_is_hot", property="productIsHot", jdbcType=JdbcType.INTEGER),
        @Result(column="product_is_commend", property="productIsCommend", jdbcType=JdbcType.INTEGER),
        @Result(column="product_is_show", property="productIsShow", jdbcType=JdbcType.INTEGER),
        @Result(column="product_sales", property="productSales", jdbcType=JdbcType.INTEGER),
        @Result(column="product_colors", property="productColors", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_sizes", property="productSizes", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_features", property="productFeatures", jdbcType=JdbcType.VARCHAR),
        @Result(column="check_user_id", property="checkUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_check_time", property="productCheckTime", jdbcType=JdbcType.DATE),
        @Result(column="product_description", property="productDescription", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="product_information", property="productInformation", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="product_after_sale", property="productAfterSale", jdbcType=JdbcType.LONGVARCHAR)
    })
    EshopProductWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @UpdateProvider(type=EshopProductSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopProductWithBLOBs record, @Param("example") EshopProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @UpdateProvider(type=EshopProductSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") EshopProductWithBLOBs record, @Param("example") EshopProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @UpdateProvider(type=EshopProductSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopProduct record, @Param("example") EshopProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @UpdateProvider(type=EshopProductSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Update({
        "update eshop_product",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "brand_id = #{brandId,jdbcType=VARCHAR},",
          "type_id = #{typeId,jdbcType=VARCHAR},",
          "product_name = #{productName,jdbcType=VARCHAR},",
          "product_weight = #{productWeight,jdbcType=VARCHAR},",
          "product_is_new = #{productIsNew,jdbcType=INTEGER},",
          "product_is_hot = #{productIsHot,jdbcType=INTEGER},",
          "product_is_commend = #{productIsCommend,jdbcType=INTEGER},",
          "product_is_show = #{productIsShow,jdbcType=INTEGER},",
          "product_sales = #{productSales,jdbcType=INTEGER},",
          "product_colors = #{productColors,jdbcType=VARCHAR},",
          "product_sizes = #{productSizes,jdbcType=VARCHAR},",
          "product_features = #{productFeatures,jdbcType=VARCHAR},",
          "check_user_id = #{checkUserId,jdbcType=VARCHAR},",
          "product_check_time = #{productCheckTime,jdbcType=DATE},",
          "product_description = #{productDescription,jdbcType=LONGVARCHAR},",
          "product_information = #{productInformation,jdbcType=LONGVARCHAR},",
          "product_after_sale = #{productAfterSale,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(EshopProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    @Update({
        "update eshop_product",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "brand_id = #{brandId,jdbcType=VARCHAR},",
          "type_id = #{typeId,jdbcType=VARCHAR},",
          "product_name = #{productName,jdbcType=VARCHAR},",
          "product_weight = #{productWeight,jdbcType=VARCHAR},",
          "product_is_new = #{productIsNew,jdbcType=INTEGER},",
          "product_is_hot = #{productIsHot,jdbcType=INTEGER},",
          "product_is_commend = #{productIsCommend,jdbcType=INTEGER},",
          "product_is_show = #{productIsShow,jdbcType=INTEGER},",
          "product_sales = #{productSales,jdbcType=INTEGER},",
          "product_colors = #{productColors,jdbcType=VARCHAR},",
          "product_sizes = #{productSizes,jdbcType=VARCHAR},",
          "product_features = #{productFeatures,jdbcType=VARCHAR},",
          "check_user_id = #{checkUserId,jdbcType=VARCHAR},",
          "product_check_time = #{productCheckTime,jdbcType=DATE}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopProduct record);

    @ResultType(EshopProductWithBLOBs.class)
    @ResultMap("productsWithBLOBsResultMap")
    List<EshopProductWithBLOBs> getProducts(
            @Param("productName") String productName,
            @Param("type") String type,
            @Param("types_set") Set<String> types_set,
            @Param("prices_set") Set<String> prices_set,
            @Param("colors_set") Set<String> colors_set,
            @Param("brands_set") Set<String> brands_set,
            @Param("sizes_set") Set<String> sizes_set);
}