package online.shixun.demo.eshop.eshopserviceproduct.module.product.mapper;

import online.shixun.demo.eshop.eshopserviceproduct.dto.EshopProductCriteria.Criteria;
import online.shixun.demo.eshop.eshopserviceproduct.dto.EshopProductCriteria.Criterion;
import online.shixun.demo.eshop.eshopserviceproduct.dto.EshopProductCriteria;
import online.shixun.demo.eshop.eshopserviceproduct.dto.EshopProductWithBLOBs;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class EshopProductSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String countByExample(EshopProductCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("eshop_product");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String deleteByExample(EshopProductCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("eshop_product");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String insertSelective(EshopProductWithBLOBs record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("eshop_product");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.VALUES("is_del", "#{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=DATE}");
        }
        
        if (record.getBrandId() != null) {
            sql.VALUES("brand_id", "#{brandId,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeId() != null) {
            sql.VALUES("type_id", "#{typeId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductName() != null) {
            sql.VALUES("product_name", "#{productName,jdbcType=VARCHAR}");
        }
        
        if (record.getProductWeight() != null) {
            sql.VALUES("product_weight", "#{productWeight,jdbcType=VARCHAR}");
        }
        
        if (record.getProductIsNew() != null) {
            sql.VALUES("product_is_new", "#{productIsNew,jdbcType=INTEGER}");
        }
        
        if (record.getProductIsHot() != null) {
            sql.VALUES("product_is_hot", "#{productIsHot,jdbcType=INTEGER}");
        }
        
        if (record.getProductIsCommend() != null) {
            sql.VALUES("product_is_commend", "#{productIsCommend,jdbcType=INTEGER}");
        }
        
        if (record.getProductIsShow() != null) {
            sql.VALUES("product_is_show", "#{productIsShow,jdbcType=INTEGER}");
        }
        
        if (record.getProductSales() != null) {
            sql.VALUES("product_sales", "#{productSales,jdbcType=INTEGER}");
        }
        
        if (record.getProductColors() != null) {
            sql.VALUES("product_colors", "#{productColors,jdbcType=VARCHAR}");
        }
        
        if (record.getProductSizes() != null) {
            sql.VALUES("product_sizes", "#{productSizes,jdbcType=VARCHAR}");
        }
        
        if (record.getProductFeatures() != null) {
            sql.VALUES("product_features", "#{productFeatures,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckUserId() != null) {
            sql.VALUES("check_user_id", "#{checkUserId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductCheckTime() != null) {
            sql.VALUES("product_check_time", "#{productCheckTime,jdbcType=DATE}");
        }
        
        if (record.getProductDescription() != null) {
            sql.VALUES("product_description", "#{productDescription,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getProductInformation() != null) {
            sql.VALUES("product_information", "#{productInformation,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getProductAfterSale() != null) {
            sql.VALUES("product_after_sale", "#{productAfterSale,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String selectByExampleWithBLOBs(EshopProductCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("is_del");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.SELECT("brand_id");
        sql.SELECT("type_id");
        sql.SELECT("product_name");
        sql.SELECT("product_weight");
        sql.SELECT("product_is_new");
        sql.SELECT("product_is_hot");
        sql.SELECT("product_is_commend");
        sql.SELECT("product_is_show");
        sql.SELECT("product_sales");
        sql.SELECT("product_colors");
        sql.SELECT("product_sizes");
        sql.SELECT("product_features");
        sql.SELECT("check_user_id");
        sql.SELECT("product_check_time");
        sql.SELECT("product_description");
        sql.SELECT("product_information");
        sql.SELECT("product_after_sale");
        sql.FROM("eshop_product");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String selectByExample(EshopProductCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("is_del");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.SELECT("brand_id");
        sql.SELECT("type_id");
        sql.SELECT("product_name");
        sql.SELECT("product_weight");
        sql.SELECT("product_is_new");
        sql.SELECT("product_is_hot");
        sql.SELECT("product_is_commend");
        sql.SELECT("product_is_show");
        sql.SELECT("product_sales");
        sql.SELECT("product_colors");
        sql.SELECT("product_sizes");
        sql.SELECT("product_features");
        sql.SELECT("check_user_id");
        sql.SELECT("product_check_time");
        sql.FROM("eshop_product");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        EshopProductWithBLOBs record = (EshopProductWithBLOBs) parameter.get("record");
        EshopProductCriteria example = (EshopProductCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("eshop_product");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        }
        
        if (record.getBrandId() != null) {
            sql.SET("brand_id = #{record.brandId,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeId() != null) {
            sql.SET("type_id = #{record.typeId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductName() != null) {
            sql.SET("product_name = #{record.productName,jdbcType=VARCHAR}");
        }
        
        if (record.getProductWeight() != null) {
            sql.SET("product_weight = #{record.productWeight,jdbcType=VARCHAR}");
        }
        
        if (record.getProductIsNew() != null) {
            sql.SET("product_is_new = #{record.productIsNew,jdbcType=INTEGER}");
        }
        
        if (record.getProductIsHot() != null) {
            sql.SET("product_is_hot = #{record.productIsHot,jdbcType=INTEGER}");
        }
        
        if (record.getProductIsCommend() != null) {
            sql.SET("product_is_commend = #{record.productIsCommend,jdbcType=INTEGER}");
        }
        
        if (record.getProductIsShow() != null) {
            sql.SET("product_is_show = #{record.productIsShow,jdbcType=INTEGER}");
        }
        
        if (record.getProductSales() != null) {
            sql.SET("product_sales = #{record.productSales,jdbcType=INTEGER}");
        }
        
        if (record.getProductColors() != null) {
            sql.SET("product_colors = #{record.productColors,jdbcType=VARCHAR}");
        }
        
        if (record.getProductSizes() != null) {
            sql.SET("product_sizes = #{record.productSizes,jdbcType=VARCHAR}");
        }
        
        if (record.getProductFeatures() != null) {
            sql.SET("product_features = #{record.productFeatures,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckUserId() != null) {
            sql.SET("check_user_id = #{record.checkUserId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductCheckTime() != null) {
            sql.SET("product_check_time = #{record.productCheckTime,jdbcType=DATE}");
        }
        
        if (record.getProductDescription() != null) {
            sql.SET("product_description = #{record.productDescription,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getProductInformation() != null) {
            sql.SET("product_information = #{record.productInformation,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getProductAfterSale() != null) {
            sql.SET("product_after_sale = #{record.productAfterSale,jdbcType=LONGVARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_product");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        sql.SET("brand_id = #{record.brandId,jdbcType=VARCHAR}");
        sql.SET("type_id = #{record.typeId,jdbcType=VARCHAR}");
        sql.SET("product_name = #{record.productName,jdbcType=VARCHAR}");
        sql.SET("product_weight = #{record.productWeight,jdbcType=VARCHAR}");
        sql.SET("product_is_new = #{record.productIsNew,jdbcType=INTEGER}");
        sql.SET("product_is_hot = #{record.productIsHot,jdbcType=INTEGER}");
        sql.SET("product_is_commend = #{record.productIsCommend,jdbcType=INTEGER}");
        sql.SET("product_is_show = #{record.productIsShow,jdbcType=INTEGER}");
        sql.SET("product_sales = #{record.productSales,jdbcType=INTEGER}");
        sql.SET("product_colors = #{record.productColors,jdbcType=VARCHAR}");
        sql.SET("product_sizes = #{record.productSizes,jdbcType=VARCHAR}");
        sql.SET("product_features = #{record.productFeatures,jdbcType=VARCHAR}");
        sql.SET("check_user_id = #{record.checkUserId,jdbcType=VARCHAR}");
        sql.SET("product_check_time = #{record.productCheckTime,jdbcType=DATE}");
        sql.SET("product_description = #{record.productDescription,jdbcType=LONGVARCHAR}");
        sql.SET("product_information = #{record.productInformation,jdbcType=LONGVARCHAR}");
        sql.SET("product_after_sale = #{record.productAfterSale,jdbcType=LONGVARCHAR}");
        
        EshopProductCriteria example = (EshopProductCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_product");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        sql.SET("brand_id = #{record.brandId,jdbcType=VARCHAR}");
        sql.SET("type_id = #{record.typeId,jdbcType=VARCHAR}");
        sql.SET("product_name = #{record.productName,jdbcType=VARCHAR}");
        sql.SET("product_weight = #{record.productWeight,jdbcType=VARCHAR}");
        sql.SET("product_is_new = #{record.productIsNew,jdbcType=INTEGER}");
        sql.SET("product_is_hot = #{record.productIsHot,jdbcType=INTEGER}");
        sql.SET("product_is_commend = #{record.productIsCommend,jdbcType=INTEGER}");
        sql.SET("product_is_show = #{record.productIsShow,jdbcType=INTEGER}");
        sql.SET("product_sales = #{record.productSales,jdbcType=INTEGER}");
        sql.SET("product_colors = #{record.productColors,jdbcType=VARCHAR}");
        sql.SET("product_sizes = #{record.productSizes,jdbcType=VARCHAR}");
        sql.SET("product_features = #{record.productFeatures,jdbcType=VARCHAR}");
        sql.SET("check_user_id = #{record.checkUserId,jdbcType=VARCHAR}");
        sql.SET("product_check_time = #{record.productCheckTime,jdbcType=DATE}");
        
        EshopProductCriteria example = (EshopProductCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    public String updateByPrimaryKeySelective(EshopProductWithBLOBs record) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_product");
        
        if (record.getIsDel() != null) {
            sql.SET("is_del = #{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        
        if (record.getBrandId() != null) {
            sql.SET("brand_id = #{brandId,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeId() != null) {
            sql.SET("type_id = #{typeId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductName() != null) {
            sql.SET("product_name = #{productName,jdbcType=VARCHAR}");
        }
        
        if (record.getProductWeight() != null) {
            sql.SET("product_weight = #{productWeight,jdbcType=VARCHAR}");
        }
        
        if (record.getProductIsNew() != null) {
            sql.SET("product_is_new = #{productIsNew,jdbcType=INTEGER}");
        }
        
        if (record.getProductIsHot() != null) {
            sql.SET("product_is_hot = #{productIsHot,jdbcType=INTEGER}");
        }
        
        if (record.getProductIsCommend() != null) {
            sql.SET("product_is_commend = #{productIsCommend,jdbcType=INTEGER}");
        }
        
        if (record.getProductIsShow() != null) {
            sql.SET("product_is_show = #{productIsShow,jdbcType=INTEGER}");
        }
        
        if (record.getProductSales() != null) {
            sql.SET("product_sales = #{productSales,jdbcType=INTEGER}");
        }
        
        if (record.getProductColors() != null) {
            sql.SET("product_colors = #{productColors,jdbcType=VARCHAR}");
        }
        
        if (record.getProductSizes() != null) {
            sql.SET("product_sizes = #{productSizes,jdbcType=VARCHAR}");
        }
        
        if (record.getProductFeatures() != null) {
            sql.SET("product_features = #{productFeatures,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckUserId() != null) {
            sql.SET("check_user_id = #{checkUserId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductCheckTime() != null) {
            sql.SET("product_check_time = #{productCheckTime,jdbcType=DATE}");
        }
        
        if (record.getProductDescription() != null) {
            sql.SET("product_description = #{productDescription,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getProductInformation() != null) {
            sql.SET("product_information = #{productInformation,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getProductAfterSale() != null) {
            sql.SET("product_after_sale = #{productAfterSale,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_product
     *
     * @mbg.generated Fri May 11 10:31:51 CST 2018
     */
    protected void applyWhere(SQL sql, EshopProductCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}