package online.shixun.demo.eshop.eshopserviceresource.module.resource.mapper;

import online.shixun.demo.eshop.eshopserviceresource.dto.EshopResource;
import online.shixun.demo.eshop.eshopserviceresource.dto.EshopResourceCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Mapper
public interface EshopResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    @SelectProvider(type=EshopResourceSqlProvider.class, method="countByExample")
    long countByExample(EshopResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    @DeleteProvider(type=EshopResourceSqlProvider.class, method="deleteByExample")
    int deleteByExample(EshopResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    @Delete({
        "delete from eshop_resource",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    @Insert({
        "insert into eshop_resource (id, is_del, ",
        "create_time, update_time, ",
        "resource_name, resource_parent_id, ",
        "resource_url, resource_ico, ",
        "resource_index, resource_description, ",
        "resource_image)",
        "values (#{id,jdbcType=VARCHAR}, #{isDel,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=DATE}, #{updateTime,jdbcType=DATE}, ",
        "#{resourceName,jdbcType=VARCHAR}, #{resourceParentId,jdbcType=VARCHAR}, ",
        "#{resourceUrl,jdbcType=VARCHAR}, #{resourceIco,jdbcType=VARCHAR}, ",
        "#{resourceIndex,jdbcType=INTEGER}, #{resourceDescription,jdbcType=VARCHAR}, ",
        "#{resourceImage,jdbcType=VARCHAR})"
    })
    int insert(EshopResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    @InsertProvider(type=EshopResourceSqlProvider.class, method="insertSelective")
    int insertSelective(EshopResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    @SelectProvider(type=EshopResourceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="resource_name", property="resourceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_parent_id", property="resourceParentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_url", property="resourceUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_ico", property="resourceIco", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_index", property="resourceIndex", jdbcType=JdbcType.INTEGER),
        @Result(column="resource_description", property="resourceDescription", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_image", property="resourceImage", jdbcType=JdbcType.VARCHAR)
    })
    List<EshopResource> selectByExample(EshopResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    @Select({
        "select",
        "id, is_del, create_time, update_time, resource_name, resource_parent_id, resource_url, ",
        "resource_ico, resource_index, resource_description, resource_image",
        "from eshop_resource",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
        @Result(column="resource_name", property="resourceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_parent_id", property="resourceParentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_url", property="resourceUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_ico", property="resourceIco", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_index", property="resourceIndex", jdbcType=JdbcType.INTEGER),
        @Result(column="resource_description", property="resourceDescription", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_image", property="resourceImage", jdbcType=JdbcType.VARCHAR)
    })
    EshopResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    @UpdateProvider(type=EshopResourceSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EshopResource record, @Param("example") EshopResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    @UpdateProvider(type=EshopResourceSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EshopResource record, @Param("example") EshopResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    @UpdateProvider(type=EshopResourceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EshopResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    @Update({
        "update eshop_resource",
        "set is_del = #{isDel,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=DATE},",
          "update_time = #{updateTime,jdbcType=DATE},",
          "resource_name = #{resourceName,jdbcType=VARCHAR},",
          "resource_parent_id = #{resourceParentId,jdbcType=VARCHAR},",
          "resource_url = #{resourceUrl,jdbcType=VARCHAR},",
          "resource_ico = #{resourceIco,jdbcType=VARCHAR},",
          "resource_index = #{resourceIndex,jdbcType=INTEGER},",
          "resource_description = #{resourceDescription,jdbcType=VARCHAR},",
          "resource_image = #{resourceImage,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EshopResource record);

    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="is_del", property="isDel", jdbcType=JdbcType.INTEGER),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
            @Result(column="resource_name", property="resourceName", jdbcType=JdbcType.VARCHAR),
            @Result(column="resource_parent_id", property="resourceParentId", jdbcType=JdbcType.VARCHAR),
            @Result(column="resource_url", property="resourceUrl", jdbcType=JdbcType.VARCHAR),
            @Result(column="resource_ico", property="resourceIco", jdbcType=JdbcType.VARCHAR),
            @Result(column="resource_index", property="resourceIndex", jdbcType=JdbcType.INTEGER),
            @Result(column="resource_description", property="resourceDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="resource_image", property="resourceImage", jdbcType=JdbcType.VARCHAR)
    })
    @Select(value = "SELECT * FROM `eshop_resource` WHERE `resource_parent_id` = #{id} and is_del=2 ")
    List<EshopResource> findChildren(@Param("id") String id);
}