package online.shixun.demo.eshop.eshopserviceresource.module.resource.mapper;

import online.shixun.demo.eshop.eshopserviceresource.dto.EshopResource;
import online.shixun.demo.eshop.eshopserviceresource.dto.EshopResourceCriteria;
import online.shixun.demo.eshop.eshopserviceresource.dto.EshopResourceCriteria.Criteria;
import online.shixun.demo.eshop.eshopserviceresource.dto.EshopResourceCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class EshopResourceSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    public String countByExample(EshopResourceCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("eshop_resource");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    public String deleteByExample(EshopResourceCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("eshop_resource");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    public String insertSelective(EshopResource record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("eshop_resource");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.VALUES("is_del", "#{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=DATE}");
        }
        
        if (record.getResourceName() != null) {
            sql.VALUES("resource_name", "#{resourceName,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceParentId() != null) {
            sql.VALUES("resource_parent_id", "#{resourceParentId,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceUrl() != null) {
            sql.VALUES("resource_url", "#{resourceUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceIco() != null) {
            sql.VALUES("resource_ico", "#{resourceIco,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceIndex() != null) {
            sql.VALUES("resource_index", "#{resourceIndex,jdbcType=INTEGER}");
        }
        
        if (record.getResourceDescription() != null) {
            sql.VALUES("resource_description", "#{resourceDescription,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceImage() != null) {
            sql.VALUES("resource_image", "#{resourceImage,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    public String selectByExample(EshopResourceCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("is_del");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.SELECT("resource_name");
        sql.SELECT("resource_parent_id");
        sql.SELECT("resource_url");
        sql.SELECT("resource_ico");
        sql.SELECT("resource_index");
        sql.SELECT("resource_description");
        sql.SELECT("resource_image");
        sql.FROM("eshop_resource");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        EshopResource record = (EshopResource) parameter.get("record");
        EshopResourceCriteria example = (EshopResourceCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("eshop_resource");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        }
        
        if (record.getResourceName() != null) {
            sql.SET("resource_name = #{record.resourceName,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceParentId() != null) {
            sql.SET("resource_parent_id = #{record.resourceParentId,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceUrl() != null) {
            sql.SET("resource_url = #{record.resourceUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceIco() != null) {
            sql.SET("resource_ico = #{record.resourceIco,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceIndex() != null) {
            sql.SET("resource_index = #{record.resourceIndex,jdbcType=INTEGER}");
        }
        
        if (record.getResourceDescription() != null) {
            sql.SET("resource_description = #{record.resourceDescription,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceImage() != null) {
            sql.SET("resource_image = #{record.resourceImage,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_resource");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("is_del = #{record.isDel,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=DATE}");
        sql.SET("update_time = #{record.updateTime,jdbcType=DATE}");
        sql.SET("resource_name = #{record.resourceName,jdbcType=VARCHAR}");
        sql.SET("resource_parent_id = #{record.resourceParentId,jdbcType=VARCHAR}");
        sql.SET("resource_url = #{record.resourceUrl,jdbcType=VARCHAR}");
        sql.SET("resource_ico = #{record.resourceIco,jdbcType=VARCHAR}");
        sql.SET("resource_index = #{record.resourceIndex,jdbcType=INTEGER}");
        sql.SET("resource_description = #{record.resourceDescription,jdbcType=VARCHAR}");
        sql.SET("resource_image = #{record.resourceImage,jdbcType=VARCHAR}");
        
        EshopResourceCriteria example = (EshopResourceCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    public String updateByPrimaryKeySelective(EshopResource record) {
        SQL sql = new SQL();
        sql.UPDATE("eshop_resource");
        
        if (record.getIsDel() != null) {
            sql.SET("is_del = #{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        
        if (record.getResourceName() != null) {
            sql.SET("resource_name = #{resourceName,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceParentId() != null) {
            sql.SET("resource_parent_id = #{resourceParentId,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceUrl() != null) {
            sql.SET("resource_url = #{resourceUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceIco() != null) {
            sql.SET("resource_ico = #{resourceIco,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceIndex() != null) {
            sql.SET("resource_index = #{resourceIndex,jdbcType=INTEGER}");
        }
        
        if (record.getResourceDescription() != null) {
            sql.SET("resource_description = #{resourceDescription,jdbcType=VARCHAR}");
        }
        
        if (record.getResourceImage() != null) {
            sql.SET("resource_image = #{resourceImage,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_resource
     *
     * @mbg.generated Fri May 11 10:30:06 CST 2018
     */
    protected void applyWhere(SQL sql, EshopResourceCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}