package online.shixun.demo.eshop.eshopserviceslideshow.dto;

import java.io.Serializable;
import java.util.Date;

public class EshopSlideshow implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_slideshow.id
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_slideshow.is_del
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_slideshow.create_time
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_slideshow.update_time
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_slideshow.slideshow_name
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    private String slideshowName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_slideshow.slideshow_url
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    private String slideshowUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_slideshow.slideshow_index
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    private Integer slideshowIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_slideshow.slideshow_html
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    private String slideshowHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eshop_slideshow.slideshow_image
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    private String slideshowImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_slideshow.id
     *
     * @return the value of eshop_slideshow.id
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_slideshow.id
     *
     * @param id the value for eshop_slideshow.id
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_slideshow.is_del
     *
     * @return the value of eshop_slideshow.is_del
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_slideshow.is_del
     *
     * @param isDel the value for eshop_slideshow.is_del
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_slideshow.create_time
     *
     * @return the value of eshop_slideshow.create_time
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_slideshow.create_time
     *
     * @param createTime the value for eshop_slideshow.create_time
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_slideshow.update_time
     *
     * @return the value of eshop_slideshow.update_time
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_slideshow.update_time
     *
     * @param updateTime the value for eshop_slideshow.update_time
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_slideshow.slideshow_name
     *
     * @return the value of eshop_slideshow.slideshow_name
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String getSlideshowName() {
        return slideshowName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_slideshow.slideshow_name
     *
     * @param slideshowName the value for eshop_slideshow.slideshow_name
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void setSlideshowName(String slideshowName) {
        this.slideshowName = slideshowName == null ? null : slideshowName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_slideshow.slideshow_url
     *
     * @return the value of eshop_slideshow.slideshow_url
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String getSlideshowUrl() {
        return slideshowUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_slideshow.slideshow_url
     *
     * @param slideshowUrl the value for eshop_slideshow.slideshow_url
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void setSlideshowUrl(String slideshowUrl) {
        this.slideshowUrl = slideshowUrl == null ? null : slideshowUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_slideshow.slideshow_index
     *
     * @return the value of eshop_slideshow.slideshow_index
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public Integer getSlideshowIndex() {
        return slideshowIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_slideshow.slideshow_index
     *
     * @param slideshowIndex the value for eshop_slideshow.slideshow_index
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void setSlideshowIndex(Integer slideshowIndex) {
        this.slideshowIndex = slideshowIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_slideshow.slideshow_html
     *
     * @return the value of eshop_slideshow.slideshow_html
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String getSlideshowHtml() {
        return slideshowHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_slideshow.slideshow_html
     *
     * @param slideshowHtml the value for eshop_slideshow.slideshow_html
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void setSlideshowHtml(String slideshowHtml) {
        this.slideshowHtml = slideshowHtml == null ? null : slideshowHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eshop_slideshow.slideshow_image
     *
     * @return the value of eshop_slideshow.slideshow_image
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String getSlideshowImage() {
        return slideshowImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eshop_slideshow.slideshow_image
     *
     * @param slideshowImage the value for eshop_slideshow.slideshow_image
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void setSlideshowImage(String slideshowImage) {
        this.slideshowImage = slideshowImage == null ? null : slideshowImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", slideshowName=").append(slideshowName);
        sb.append(", slideshowUrl=").append(slideshowUrl);
        sb.append(", slideshowIndex=").append(slideshowIndex);
        sb.append(", slideshowHtml=").append(slideshowHtml);
        sb.append(", slideshowImage=").append(slideshowImage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}