package online.shixun.demo.eshop.eshopserviceslideshow.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EshopSlideshowCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public EshopSlideshowCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Integer value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Integer value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Integer value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Integer value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Integer value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Integer> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Integer> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Integer value1, Integer value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Integer value1, Integer value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterionForJDBCDate("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameIsNull() {
            addCriterion("slideshow_name is null");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameIsNotNull() {
            addCriterion("slideshow_name is not null");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameEqualTo(String value) {
            addCriterion("slideshow_name =", value, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameNotEqualTo(String value) {
            addCriterion("slideshow_name <>", value, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameGreaterThan(String value) {
            addCriterion("slideshow_name >", value, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameGreaterThanOrEqualTo(String value) {
            addCriterion("slideshow_name >=", value, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameLessThan(String value) {
            addCriterion("slideshow_name <", value, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameLessThanOrEqualTo(String value) {
            addCriterion("slideshow_name <=", value, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameLike(String value) {
            addCriterion("slideshow_name like", value, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameNotLike(String value) {
            addCriterion("slideshow_name not like", value, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameIn(List<String> values) {
            addCriterion("slideshow_name in", values, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameNotIn(List<String> values) {
            addCriterion("slideshow_name not in", values, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameBetween(String value1, String value2) {
            addCriterion("slideshow_name between", value1, value2, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowNameNotBetween(String value1, String value2) {
            addCriterion("slideshow_name not between", value1, value2, "slideshowName");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlIsNull() {
            addCriterion("slideshow_url is null");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlIsNotNull() {
            addCriterion("slideshow_url is not null");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlEqualTo(String value) {
            addCriterion("slideshow_url =", value, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlNotEqualTo(String value) {
            addCriterion("slideshow_url <>", value, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlGreaterThan(String value) {
            addCriterion("slideshow_url >", value, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlGreaterThanOrEqualTo(String value) {
            addCriterion("slideshow_url >=", value, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlLessThan(String value) {
            addCriterion("slideshow_url <", value, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlLessThanOrEqualTo(String value) {
            addCriterion("slideshow_url <=", value, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlLike(String value) {
            addCriterion("slideshow_url like", value, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlNotLike(String value) {
            addCriterion("slideshow_url not like", value, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlIn(List<String> values) {
            addCriterion("slideshow_url in", values, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlNotIn(List<String> values) {
            addCriterion("slideshow_url not in", values, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlBetween(String value1, String value2) {
            addCriterion("slideshow_url between", value1, value2, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowUrlNotBetween(String value1, String value2) {
            addCriterion("slideshow_url not between", value1, value2, "slideshowUrl");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexIsNull() {
            addCriterion("slideshow_index is null");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexIsNotNull() {
            addCriterion("slideshow_index is not null");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexEqualTo(Integer value) {
            addCriterion("slideshow_index =", value, "slideshowIndex");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexNotEqualTo(Integer value) {
            addCriterion("slideshow_index <>", value, "slideshowIndex");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexGreaterThan(Integer value) {
            addCriterion("slideshow_index >", value, "slideshowIndex");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("slideshow_index >=", value, "slideshowIndex");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexLessThan(Integer value) {
            addCriterion("slideshow_index <", value, "slideshowIndex");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexLessThanOrEqualTo(Integer value) {
            addCriterion("slideshow_index <=", value, "slideshowIndex");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexIn(List<Integer> values) {
            addCriterion("slideshow_index in", values, "slideshowIndex");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexNotIn(List<Integer> values) {
            addCriterion("slideshow_index not in", values, "slideshowIndex");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexBetween(Integer value1, Integer value2) {
            addCriterion("slideshow_index between", value1, value2, "slideshowIndex");
            return (Criteria) this;
        }

        public Criteria andSlideshowIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("slideshow_index not between", value1, value2, "slideshowIndex");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlIsNull() {
            addCriterion("slideshow_html is null");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlIsNotNull() {
            addCriterion("slideshow_html is not null");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlEqualTo(String value) {
            addCriterion("slideshow_html =", value, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlNotEqualTo(String value) {
            addCriterion("slideshow_html <>", value, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlGreaterThan(String value) {
            addCriterion("slideshow_html >", value, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlGreaterThanOrEqualTo(String value) {
            addCriterion("slideshow_html >=", value, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlLessThan(String value) {
            addCriterion("slideshow_html <", value, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlLessThanOrEqualTo(String value) {
            addCriterion("slideshow_html <=", value, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlLike(String value) {
            addCriterion("slideshow_html like", value, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlNotLike(String value) {
            addCriterion("slideshow_html not like", value, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlIn(List<String> values) {
            addCriterion("slideshow_html in", values, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlNotIn(List<String> values) {
            addCriterion("slideshow_html not in", values, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlBetween(String value1, String value2) {
            addCriterion("slideshow_html between", value1, value2, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowHtmlNotBetween(String value1, String value2) {
            addCriterion("slideshow_html not between", value1, value2, "slideshowHtml");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageIsNull() {
            addCriterion("slideshow_image is null");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageIsNotNull() {
            addCriterion("slideshow_image is not null");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageEqualTo(String value) {
            addCriterion("slideshow_image =", value, "slideshowImage");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageNotEqualTo(String value) {
            addCriterion("slideshow_image <>", value, "slideshowImage");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageGreaterThan(String value) {
            addCriterion("slideshow_image >", value, "slideshowImage");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageGreaterThanOrEqualTo(String value) {
            addCriterion("slideshow_image >=", value, "slideshowImage");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageLessThan(String value) {
            addCriterion("slideshow_image <", value, "slideshowImage");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageLessThanOrEqualTo(String value) {
            addCriterion("slideshow_image <=", value, "slideshowImage");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageLike(String value) {
            addCriterion("slideshow_image like", value, "slideshowImage");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageNotLike(String value) {
            addCriterion("slideshow_image not like", value, "slideshowImage");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageIn(List<String> values) {
            addCriterion("slideshow_image in", values, "slideshowImage");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageNotIn(List<String> values) {
            addCriterion("slideshow_image not in", values, "slideshowImage");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageBetween(String value1, String value2) {
            addCriterion("slideshow_image between", value1, value2, "slideshowImage");
            return (Criteria) this;
        }

        public Criteria andSlideshowImageNotBetween(String value1, String value2) {
            addCriterion("slideshow_image not between", value1, value2, "slideshowImage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_slideshow
     *
     * @mbg.generated do_not_delete_during_merge Tue May 22 16:37:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eshop_slideshow
     *
     * @mbg.generated Tue May 22 16:37:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}